### ISSUE TITLE
Error after logging in to onedata panel

### ISSUE THREAD

**Issue by nanjiangshu** [onedata/onedata#1]
Hi,

I got this error directly after logging in to the onedata server page

ERROR:  error:{badmatch,{error,[70,97,105,108,117,114,101,32,111,110,32,97,108,108,32,110,111,100,101,115,46]}}

STACK: 	page_spaces_management:body/0:102
	page_spaces_management:main/0:60
	wf_core:run/1:15
	n2o_handler:handle/2:39
	cowboy_handler:handler_handle/4:111
	cowboy_protocol:execute/4:442

The command I used to start the onedata is 

$ ./run_onedata.sh --oneprovider -n 1 --oneprovider-data-dir "/media/storage" 

The same error occured when I used the default command to start onedata daemon

$ ./run_onedata.sh --oneprovider 

No error message was shown from the command line when I started the onedata server 

Any ideas?

Best,

Nanjiang

P.S. below I pasted also the full log of the two commands I used to start onedata the onedata server

$ ./run_onedata.sh --oneprovider -n 1 --oneprovider-data-dir "/media/storage" 
IMPORTANT: After each start wait for a message: Congratulations! oneprovider has been successfully started.
To ensure that the oneprovider is completely setup.
Pulling node1.oneprovider.onedata.example.com (onedata/oneprovider:3.0.0-RC1)...
3.0.0-RC1: Pulling from onedata/oneprovider
Digest: sha256:45426ad8227f909716eb30ce149cda415cc26e64b44de80118409fa91009348f
Status: Image is up to date for onedata/oneprovider:3.0.0-RC1
Starting 10oneprovideronedataorg_node1.oneprovider.onedata.example.com_1
Attaching to 10oneprovideronedataorg_node1.oneprovider.onedata.example.com_1
node1.oneprovider.onedata.example.com_1  | Starting op_panel: [  OK  ]
node1.oneprovider.onedata.example.com_1  | Starting couchbase-server: [  OK  ]
node1.oneprovider.onedata.example.com_1  | Starting cluster_manager: [  OK  ]
node1.oneprovider.onedata.example.com_1  | 
node1.oneprovider.onedata.example.com_1  | Congratulations! oneprovider has been successfully started.
node1.oneprovider.onedata.example.com_1  | 
node1.oneprovider.onedata.example.com_1  | Container details:
node1.oneprovider.onedata.example.com_1  | * IP Address: 172.18.0.2
node1.oneprovider.onedata.example.com_1  | * Ports: 0.0.0.0:53 -> 53/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:7443 -> 7443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:6666 -> 6666/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8876 -> 8876/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:5556 -> 5556/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:9443 -> 9443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8877 -> 8877/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:6665 -> 6665/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:5555 -> 5555/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:80 -> 80/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8443 -> 8443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:443 -> 443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:53 -> 53/udp
^CGracefully stopping... (press Ctrl+C again to force)
Stopping 10oneprovideronedataorg_node1.oneprovider.onedata.example.com_1 ... done
nanjiang@centos7-test1 ~/soft/getting-started/scenarios/1_0_oneprovider_onedata_org
$ ./run_onedata.sh --oneprovider 
IMPORTANT: After each start wait for a message: Congratulations! oneprovider has been successfully started.
To ensure that the oneprovider is completely setup.
Pulling node1.oneprovider.onedata.example.com (onedata/oneprovider:3.0.0-RC1)...
3.0.0-RC1: Pulling from onedata/oneprovider
Digest: sha256:45426ad8227f909716eb30ce149cda415cc26e64b44de80118409fa91009348f
Status: Image is up to date for onedata/oneprovider:3.0.0-RC1
Recreating 10oneprovideronedataorg_node1.oneprovider.onedata.example.com_1
Attaching to 10oneprovideronedataorg_node1.oneprovider.onedata.example.com_1
node1.oneprovider.onedata.example.com_1  | Starting op_panel: [  OK  ]
node1.oneprovider.onedata.example.com_1  | Starting couchbase-server: [  OK  ]
node1.oneprovider.onedata.example.com_1  | Starting cluster_manager: [  OK  ]
node1.oneprovider.onedata.example.com_1  | Starting op_worker: [  OK  ]
node1.oneprovider.onedata.example.com_1  | 
node1.oneprovider.onedata.example.com_1  | Congratulations! oneprovider has been successfully started.
node1.oneprovider.onedata.example.com_1  | 
node1.oneprovider.onedata.example.com_1  | Container details:
node1.oneprovider.onedata.example.com_1  | * IP Address: 172.18.0.2
node1.oneprovider.onedata.example.com_1  | * Ports: 0.0.0.0:53 -> 53/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:7443 -> 7443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:6666 -> 6666/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8876 -> 8876/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:5556 -> 5556/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:9443 -> 9443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8877 -> 8877/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:6665 -> 6665/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:5555 -> 5555/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:80 -> 80/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:8443 -> 8443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:443 -> 443/tcp
node1.oneprovider.onedata.example.com_1  |          0.0.0.0:53 -> 53/udp
^CGracefully stopping... (press Ctrl+C again to force)
Stopping 10oneprovideronedataorg_node1.oneprovide

**Comment by luman75** [comment]
@nanjiangshu could you try version RC2?

**Comment by nanjiangshu** [comment]
How can I run version RC2? I ran 

$ git pull
and 
$ ./onedata.sh --clean

and then run the command 
./run_onedata.sh --oneprovider -n 1 --oneprovider-data-dir "/media/storage"
again

but it is still version RC1?

Best,
Nanjiang

**Comment by groundnuty** [comment]
@nanjiangshu today we will update getting-started repo to RC3, then you can try it - please bare with us.

**Comment by nanjiangshu** [comment]
@groundnuty 
Thanks. Please let me know when the repo is updated.

**Comment by groundnuty** [comment]
@nanjiangshu please try our new RC3 and fresh getting-started version here
https://github.com/onedata/getting-started/

**Comment by nanjiangshu** [comment]
Hi,

I have updated to RC3 and started the oneprovider, but now I can not login to the admin page anymore. I have tried the (admin, password) (admin, admin) as well as (admin, my_previous_used_password). All of them returned "Authentication error". Have you changed the default password in the new version RC3?

The full log of the command is pasted below:

$ ./run_onedata.sh --provider --provider-fqdn 90.147.170.176 --provider-data-dir "/media/storage" 
IMPORTANT: After each start wait for a message: Congratulations! oneprovider has been successfully started.
To ensure that the oneprovider is completely setup.
Pulling node1.oneprovider.localhost (onedata/oneprovider:3.0.0-RC3)...
3.0.0-RC3: Pulling from onedata/oneprovider
Digest: sha256:b57c663ac5d08717db095aa8d4407dc135141646747ce1db1d949df955ac73d3
Status: Image is up to date for onedata/oneprovider:3.0.0-RC3
Creating oneprovider-1
Attaching to oneprovider-1
oneprovider-1                  | Starting op_panel: [  OK  ]
oneprovider-1                  | 
oneprovider-1                  | Configuring oneprovider:
oneprovider-1                  | * service_onepanel: set_cookie
oneprovider-1                  | * service_onepanel: purge_node
oneprovider-1                  | * service_onepanel: create_tables
oneprovider-1                  | * service_onepanel: add_nodes
oneprovider-1                  | * service: save
oneprovider-1                  | * service_couchbase: configure
oneprovider-1                  | * service_couchbase: start
oneprovider-1                  | * service_couchbase: wait_for_init
oneprovider-1                  | * service_couchbase: init_cluster
oneprovider-1                  | * service_couchbase: rebalance_cluster
oneprovider-1                  | * service_couchbase: status
oneprovider-1                  | * service: save
oneprovider-1                  | * service_cluster_manager: configure
oneprovider-1                  | * service_cluster_manager: start
oneprovider-1                  | * service_cluster_manager: status
oneprovider-1                  | * service: save
oneprovider-1                  | * service_op_worker: configure
oneprovider-1                  | * service_op_worker: start
oneprovider-1                  | * service_op_worker: wait_for_init
oneprovider-1                  | * service_op_worker: status
oneprovider-1                  | * service_op_worker: add_storages
oneprovider-1                  | * service_oneprovider: configure
oneprovider-1                  | * service_oneprovider: register
oneprovider-1                  | * service: save
oneprovider-1                  | * service_onepanel: add_users
oneprovider-1                  | 
oneprovider-1                  | Container details:
oneprovider-1                  | * IP Address: 172.19.0.2
oneprovider-1                  | * Ports: 0.0.0.0:53 -> 53/tcp
oneprovider-1                  |          0.0.0.0:7443 -> 7443/tcp
oneprovider-1                  |          0.0.0.0:6666 -> 6666/tcp
oneprovider-1                  |          0.0.0.0:8876 -> 8876/tcp
oneprovider-1                  |          0.0.0.0:5556 -> 5556/tcp
oneprovider-1                  |          0.0.0.0:9443 -> 9443/tcp
oneprovider-1                  |          0.0.0.0:8877 -> 8877/tcp
oneprovider-1                  |          0.0.0.0:6665 -> 6665/tcp
oneprovider-1                  |          0.0.0.0:5555 -> 5555/tcp
oneprovider-1                  |          0.0.0.0:80 -> 80/tcp
oneprovider-1                  |          0.0.0.0:8443 -> 8443/tcp
oneprovider-1                  |          0.0.0.0:443 -> 443/tcp
oneprovider-1                  |          0.0.0.0:53 -> 53/udp
oneprovider-1                  | 
oneprovider-1                  | Congratulations! oneprovider has been successfully started.


Best,

Nanjiang

**Comment by groundnuty** [comment]
@nanjiangshu 
yes, we updated the default password to "Password1" please try it

**Comment by nanjiangshu** [comment]
Hi, @groundnuty 

I succeeded to login to the admin page and set up a space.
Accessing to the onedata volume via the web interface is working now. Thanks very much!
I'm now trying to access the volume by oneclient via the command line. 
I tried with the scenario 2 since there is a yml config file for oneclient 

I ran the command: 
 MOUNT_POINT=/mnt/oneclient ./run_oneclient.sh --provider 90.147.170.176 --token 'MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzYmlkZW500aWZpZXIgX0096U00x6MVdQYnhFdTJwYW5VSkdoRExsZ25tMWFlZDRic00tkdVFkb00xITQowMDFhY2lkIHRpbWUgPCAxNTAzNjY00MjUwCjAwMmZzaWduYXR1cmUgWI6VuK200Mkk3gEFZRTINs3Hg6AH8lXVWVOiDxlwZ5loK'

everything seems OK. However, the folder /mnt/oneclient is empty after the command finished.
$  docker ps -a | grep oneclient
d48f6ef01342        onedata/oneclient:3.0.0-RC3     "/root/run.sh /mnt/on"   19 minutes ago      Up 19 minutes 

but the folder /mnt/on does not exist.

Any ideas?

Best,
Nanjiang

**Comment by groundnuty** [comment]
@nanjiangshu the rc4 is out please checkout https://github.com/onedata/getting-started

**Comment by nanjiangshu** [comment]
Hi @groundnuty,

I have updated to RC4 and started the run_onedata.sh again.
However, I noticed that one process 'mc:listener' is running with 100% CPU always and the data server runs really slow. I guess there's bugs in the package.

Best,

Nanjiang

**Comment by groundnuty** [comment]
but the error reported in this issue at the top is gone? if so lets open another one :)

**Comment by nanjiangshu** [comment]
@groundnuty 

Oneprovider works well with RC3, but after I have upgraded to RC4, it failed again. 

The https://90.147.170.176:9443/ shows a blank page.

**Comment by groundnuty** [comment]
@nanjiangshu as far as 'ml:listener is concerned' please you need to increase database memory limit. Here is altered scenario 1.0 config:
https://gist.github.com/groundnuty/85efe5ff909ed579cefd81d7ad7f7479
with added database quota keys. Please compare it agains your configuration.

**Comment by nanjiangshu** [comment]
Hi @groundnuty 

Now I get the error message "Cannot fetch provider details.
Please try again later." after logging in.

With or without the extra config 

"
serverQuota: 4096
bucketQuota: 2048
"

**Comment by nanjiangshu** [comment]
Is there any stable release that I can use?

Best,

Nanjiang

**Comment by groundnuty** [comment]
Please visit our support chat. We need to establish how you deploy the
provider. We had no complaints for rc4 so far.

**Comment by groundnuty** [comment]
rc4 sorted it all out.
