### ISSUE TITLE
Events and notifications

### ISSUE THREAD

**Issue by deardooley** [onedata/onedata#15]
Is there an event and/or notification system in onedata to which 3rd party applications can subscribe? What is the recommended way for an external application to subscribe for changes in data, metadata, ACL, groups, spaces, etc? How does one track transfer progress asynchronously?

**Comment by lopiola** [comment]
Sorry it took so long, but here are the answers.

There are several mechanisms that you can use, but not all of what you enumerated can be monitored. 

1. You can use the changes stream (for space admins) to monitor file related changes - locations, block distribution, ACLs in spaces: https://onedata.org/docs/doc/swagger/19.02.1/oneprovider/redoc-static.html#operation/get_space_changes

2. You can track the transfer progress having the transferId: https://onedata.org/docs/doc/swagger/19.02.1/oneprovider/redoc-static.html#operation/get_transfer_status

3. You can specify a callbackURL when creating a transfer - an asynchronous HTTP request will be made on that URL by the Oneprovider when the transfer completes, see for example here: https://onedata.org/docs/doc/swagger/19.02.1/oneprovider/redoc-static.html#operation/replicate_file

Closing the issue for now, let us know if you have any further questions.
