### ISSUE TITLE
Turning on X.509 client authentication support on the IAM breaks Onedata federated login

### ISSUE THREAD

**Issue by andreaceccanti** [onedata/onedata#17]
Recently, native X.509 client authentication was added to INDIGO IAM.
It seems that enabling such support breaks login from Onedata.
I think this is due to some SNI error in the TLS library used by  Onedata, but could really debug this.

**Comment by andreaceccanti** [comment]
@luman75 is there any progress on this?

**Comment by andreaceccanti** [comment]
Has this been fixed? or is it considered invalid?

**Comment by luman75** [comment]
@andreaceccanti fixed. But it would be great if you could confirm that somehow.

**Comment by andreaceccanti** [comment]
not fixed AFAIU. I turned X.509 authn on on iam-test and onedata.org is broken.

**Comment by andreaceccanti** [comment]
Sorry for the noise, it is indeed fixed, thanks!
