### ISSUE TITLE
Deploy cluster

### ISSUE THREAD

**Issue by mariolanno** [onedata/onedata#18]
Dear all,

I'm new on ONEDATA and I'm configuring the cluster but I receive this error...

"We are sorry, but cluster deployment failed!
The reason of failure:
Service Error"

Could you help me please?

Thanks

Mario

**Comment by groundnuty** [comment]
Please provider more details on how you deploy.

Detailed logs can be found in /var/log/ and then depending on the service
op_panel,
oz_panel,
oz_worker,
op_worker,
directories.

**Comment by mariolanno** [comment]
I reinstalled it all but always the same error.
My hostname is onedata.domain.com, on the vm.args is right insert 
"-name onedata@domain.com" ?

Thanks

**Comment by mariolanno** [comment]
But this project is just supported or not?

Mario

**Comment by groundnuty** [comment]
The project is alive and well. We need more detailed information from you. How are you deploying Onedata?
