### ISSUE TITLE
Can I mount an onedata space as a Kubernetes Persistent Volume?

### ISSUE THREAD

**Issue by andersla** [onedata/onedata#19]
I wonder if it is possible to mount an onedata space as a Kubernetes Persistent Volume

**Comment by luman75** [comment]
@andersla currently we offer docker volume plugin which works works similarly to what you need on dockers and Messos infrastructure. In case of Kubernetess we don't have currently a volume plugin for onedata yet. If there is interest for that we can include that into the roadmap. Of course we welcome any help for that.
