### ISSUE TITLE
Failed to install pre-built linux package for oneclient on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by nanjiangshu** [onedata/onedata#2]
Hi,

I was trying to install oneclient by 

wget -q -O - http://get.onedata.org/oneclient.sh | bash    # for oneclient

but failed 

The full text output from the terminal is pasted below

OK
Ign http://ftp.acc.umu.se trusty/ InRelease
Ign http://extras.ubuntu.com trusty InRelease                                  
Hit http://ftp.acc.umu.se trusty/ Release.gpg                                  
Hit http://ftp.acc.umu.se trusty/ Release                                      
Hit http://ftp.acc.umu.se trusty/ Packages                                     
Ign http://se.archive.ubuntu.com trusty InRelease                              
Ign http://dl.google.com stable InRelease                                      
Hit http://se.archive.ubuntu.com trusty-updates InRelease                      
Ign http://ftp.acc.umu.se trusty/ Translation-en_US                            
Hit http://se.archive.ubuntu.com trusty-backports InRelease                    
Ign http://ftp.acc.umu.se trusty/ Translation-en                               
Hit http://packages.onedata.org vivid InRelease                                
Hit http://packages.onedata.org trusty InRelease                               
Hit http://extras.ubuntu.com trusty Release.gpg                                
Hit https://apt.dockerproject.org ubuntu-trusty InRelease                      
Hit https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages            
Hit https://apt.dockerproject.org ubuntu-trusty/main i386 Packages             
Hit http://packages.onedata.org vivid/main amd64 Packages                      
Get:1 https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US       
Hit http://dl.google.com stable Release.gpg                                    
Hit http://dl.google.com stable Release                                        
Hit http://se.archive.ubuntu.com trusty Release.gpg                            
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://extras.ubuntu.com trusty Release                                    
Hit http://se.archive.ubuntu.com trusty-updates/main Sources                   
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US         
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en            
Hit http://se.archive.ubuntu.com trusty-updates/restricted Sources             
Ign http://repository.egi.eu squeeze InRelease                                 
Ign http://dl.google.com stable/main Translation-en_US                         
Ign http://dl.google.com stable/main Translation-en                            
Hit http://se.archive.ubuntu.com trusty-updates/universe Sources               
Ign http://repository.egi.eu squeeze-updates InRelease                         
Hit http://packages.onedata.org trusty/main Sources                            
Hit http://packages.onedata.org trusty/main amd64 Packages                     
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Hit http://se.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://se.archive.ubuntu.com trusty-updates/main amd64 Packages            
Hit http://se.archive.ubuntu.com trusty-updates/restricted amd64 Packages      
Hit http://se.archive.ubuntu.com trusty-updates/universe amd64 Packages        
Hit http://se.archive.ubuntu.com trusty-updates/multiverse amd64 Packages      
Hit http://se.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://se.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://repository.egi.eu egi-igtf InRelease                                
Ign http://repository.egi.eu trusty InRelease                                  
Hit http://se.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://se.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Hit http://se.archive.ubuntu.com trusty-updates/main Translation-en            
Ign http://packages.onedata.org trusty/main Translation-en_US                  
Ign http://packages.onedata.org trusty/main Translation-en                     
Hit http://repository.egi.eu squeeze Release.gpg                               
Hit http://se.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Hit http://se.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://se.archive.ubuntu.com trusty-updates/universe Translation-en        
Ign http://toolbelt.heroku.com ./ InRelease                                    
Hit http://repository.egi.eu squeeze-updates Release.gpg                       
Hit http://toolbelt.heroku.com ./ Release.gpg                                  
Hit http://repository.egi.eu egi-igtf/core amd64 Packages                      
Hit http://toolbelt.heroku.com ./ Release                                      
Hit http://se.archive.ubuntu.com trusty-backports/main Sources                 
Hit http://se.archive.ubuntu.com trusty-backports/restricted Sources           
Hit http://se.archive.ubuntu.com trusty-backports/universe Sources             
Hit http://toolbelt.heroku.com ./ Packages                                     
Hit http://se.archive.ubuntu.com trusty-backports/multiverse Sources           
Hit http://se.archive.ubuntu.com trusty-backports/main amd64 Packages          
Hit http://se.archive.ubuntu.com trusty-backports/restricted amd64 Packages    
Hit http://se.archive.ubuntu.com trusty-backports/universe amd64 Packages      
Ign http://toolbelt.heroku.com ./ Translation-en_US                            
Hit http://se.archive.ubuntu.com trusty-backports/multiverse amd64 Packages    
Ign http://toolbelt.heroku.com ./ Translation-en                               
Ign http://extras.ubuntu.com trusty/main Translation-en_US                     
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Hit https://packagecloud.io trusty InRelease                                   
Hit https://packagecloud.io trusty/main Sources                                
Hit https://packagecloud.io trusty/main amd64 Packages                         
Hit https://packagecloud.io trusty/main i386 Packages                          
Get:2 https://packagecloud.io trusty/main Translation-en_US                    
Hit http://se.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://repository.egi.eu egi-igtf/core i386 Packages                       
Hit http://se.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Hit http://repository.egi.eu trusty Release.gpg                                
Hit http://se.archive.ubuntu.com trusty-backports/universe i386 Packages       
Hit http://repository.egi.eu squeeze Release                                   
Hit http://se.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://repository.egi.eu squeeze-updates Release                           
Ign https://packagecloud.io trusty/main Translation-en_US                      
Ign https://packagecloud.io trusty/main Translation-en                         
Hit http://se.archive.ubuntu.com trusty-backports/main Translation-en          
Hit http://se.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://se.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://se.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://repository.egi.eu trusty Release                                    
Hit http://repository.egi.eu squeeze/main amd64 Packages                       
Hit http://se.archive.ubuntu.com trusty Release                                
Hit http://se.archive.ubuntu.com trusty/main Sources                           
Hit http://se.archive.ubuntu.com trusty/restricted Sources                     
Hit http://repository.egi.eu squeeze-updates/main amd64 Packages               
Hit http://se.archive.ubuntu.com trusty/universe Sources                       
Hit http://se.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://se.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://se.archive.ubuntu.com trusty/restricted amd64 Packages              
Hit http://se.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://se.archive.ubuntu.com trusty/multiverse amd64 Packages              
Hit http://se.archive.ubuntu.com trusty/main i386 Packages                     
Hit http://se.archive.ubuntu.com trusty/restricted i386 Packages               
Hit http://se.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://se.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://se.archive.ubuntu.com trusty/main Translation-en                    
Hit http://se.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://repository.egi.eu trusty/main amd64 Packages                        
Hit http://se.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://se.archive.ubuntu.com trusty/universe Translation-en                
Ign http://repository.egi.eu egi-igtf/core Translation-en_US                   
Ign http://repository.egi.eu egi-igtf/core Translation-en                      
Ign http://se.archive.ubuntu.com trusty/main Translation-en_US                
Ign http://se.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://se.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://se.archive.ubuntu.com trusty/universe Translation-en_US             
Hit http://security.ubuntu.com trusty-security InRelease                       
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
W: Failed to fetch http://packages.onedata.org/apt/ubuntu/dists/vivid/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://repository.egi.eu/sw/production/umd/3/debian/dists/squeeze/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://repository.egi.eu/sw/production/umd/3/debian/dists/squeeze-updates/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://repository.egi.eu/community/software/rocci.cli/4.3.x/releases/ubuntu/dists/trusty/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

Best,

Nanjiang

**Comment by groundnuty** [comment]
@nanjiangshu we need to update documentation and correct that we only support x86_64. It will not work on i386 :(

**Comment by nanjiangshu** [comment]
I was running 
wget -q -O - http://get.onedata.org/oneclient.sh | bash # for oneclient 
on x86_64 Ubuntu 14.04 LTS

**Comment by groundnuty** [comment]
ok, as I understand we solved this. On the support chat. It worked on clean Ubuntu x86_64  VM.
