### ISSUE TITLE
Possible bug in the onedatify.sh script

### ISSUE THREAD

**Issue by carmat88** [onedata/onedata#20]
Hello Folk!

As per your [documentation](https://onedata.org/#/home/documentation/doc/administering_onedata/onedatify[deploy-oneprovider-and-expose-existing-data-collection].html), we are trying the scenario for deploying Oneprovider and expose existing data collection.

However when pasting the copied command in the terminal on the Oneprovider machine (as superuser), we are getting such error:

```
Downloaded Onedatify installation script /tmp/onedatify_18.02.0.beta3.sh
chmod: cannot access '/tmp/onedatify_18.02.0.beta3.sh': No such file or directory
/tmp/onescript: 110: /tmp/onescript: /tmp/onedatify_18.02.0.beta3.sh: not found
```

By inspecting the [`onedatify.sh` script](https://get.onedata.org/), we've gone up to the URL where the script `onedatify_18.02.0.beta3.sh` is supposed to exist. Such URL is the following: https://packages.onedata.org/ . In the `onedatify` folder it is possible to find the collection of all different version for the oneprovider script, however the filename convention for beta scripts uses "_" (underscores) not "." (dots). Therefore at line 95 and 97 of [`onedatify.sh` script](https://get.onedata.org/), it should be added an extra `| tr . _` if the `onezone_version` is a beta one.

What do you think ? Should this be addressed ? Or is it an assumption that a user will always have a onezone service deployed on a dedicated VM rather than using beta.onedata.org?

Thanks for your help. Cheers!

**Comment by groundnuty** [comment]
@carmat88 Thanks for the report.  Your almost right: the filenames with `_` at `http://packages.onedata.org/onedatify/` were wrong, the script is ok ;-)
I've fixed the names of beta3 and other scripts.

You can use beta.onedata.org or any other zone and it should work fine.

Cheers,
Michal

**Comment by carmat88** [comment]
Great, thanks a lot for your help and attention @groundnuty . Have a good one. Cheers!

**Comment by luman75** [comment]
@carmat88  please be aware that currently we have version 18.02.0-rc4, so you don't need to use beta3 anymore

**Comment by carmat88** [comment]
@luman75 Alright, thanks for the heads-up. However I reckon the `onedatify.sh` script will anyway fetch automatically the version based on the onezone being used. So if I use the beta portal, then `onezone_version` should be set to `18.02.0-beta3` which will be used to create the strings `onedatify_install_script` and `onedatify_install_script_url`, is that correct to say?

Or are you suggesting to run manually `18.02.0-rc4` ?

Cheers!

**Comment by luman75** [comment]
@carmat88 To which zone are you connecting? 
Anyway you can override this behavior  specifying expected provider version in the command line of the onedatify.

**Comment by carmat88** [comment]
@luman75 As mentioned, to beta.onedata.org

Ok, nice. Thanks for the hint. Cheers!
