### ISSUE TITLE
Job for onedatify.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by carmat88** [onedata/onedata#21]
Hello again Folks! As I mentioned in this other [issue](https://github.com/onedata/onedata/issues/20) , after having slightly tweaked the code in order to be able to fetch the beta script at this [URL](https://packages.onedata.org/onedatify/), we have run the script and started to configure with the requested parameters as described [here](https://onedata.org/#/home/documentation/doc/administering_onedata/onedatify[deploy-oneprovider-and-expose-existing-data-collection].html) .

After the last question, we are getting the following error:

```
Expose storage as read only? (y/n, default: n): n
Job for onedatify.service failed because the control process exited with error code. See "systemctl status onedatify.service" and "journalctl -xe" for details.
```

and the script hangs for a long time at "`Waiting for oneprovider to start........`". This is the output we get by running `systemctl status onedatify.service` in a separate window:

```
ubuntu@carmat-onedata-test1:~$ systemctl status onedatify.service
● onedatify.service - Onedatify Service
   Loaded: loaded (/usr/lib/systemd/system/onedatify.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2018-05-29 13:40:19 UTC; 1min 23s ago
  Process: 10094 ExecStartPre=/usr/local/bin/docker-compose -f /opt/onedata/onedatify/docker-compose.yml config (code=exited, status=203/EXEC)

May 29 13:40:19 carmat-onedata-test1 systemd[1]: Failed to start Onedatify Service.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: onedatify.service: Unit entered failed state.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: onedatify.service: Failed with result 'exit-code'.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: onedatify.service: Service hold-off time over, scheduling restart.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: Stopped Onedatify Service.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: onedatify.service: Start request repeated too quickly.
May 29 13:40:19 carmat-onedata-test1 systemd[1]: Failed to start Onedatify Service.
```

Any insights that could help us correcting any configuration errors?

Many thanks. Cheers!

**Comment by luman75** [comment]
@carmat88 Could you tell us:
1. what's OS system distribution you are working with
2. To which OneZone are you working with
3. Do you have outbound connectivity to the world from that host?

**Comment by luman75** [comment]
@carmat88 recently we released reworked version of onedatify. Could you try it again, by logging to beta.onedata.org and testing the deployment again? Your test feedback will be most appreciated.
