### ISSUE TITLE
Bash onedatify_18.02.0.beta3.sh with typos and errors for RHEL installation

### ISSUE THREAD

**Issue by TomasKulhanek** [onedata/onedata#22]
Bash onedatify_18.02.0.beta3.sh with typos and errors for RHEL installation
* '-' instead of '_' in rpm path, 
* rpm command missing, 
* version 18.02.0.beta3.

These all prevents me to run the script generated by onedata web page in order to prepare my onedata provider.
Patch zipped at.
[onedatify_18.02.0.beta3.sh.zip](https://github.com/onedata/onedata/files/2149469/onedatify_18.02.0.beta3.sh.zip)

**Comment by lopiola** [comment]
Closing this as it is fixed in current stable versions.
