### ISSUE TITLE
OpenId using github fails with version 18.02.0-rc8

### ISSUE THREAD

**Issue by bertrandrigaud** [onedata/onedata#23]
Since I updated to version 18.02.0-rc8, it seems github authentication fails.
Here is the log message:

```
Query params:
[{<<"error">>,<<"redirect_uri_mismatch">>},
 {<<"error_description">>,
  <<"The redirect_uri MUST match the registered callback URL for this application.">>},
 {<<"error_uri">>,
  <<"https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch">>},
 {<<"state">>,<<"90xxxxxxxxxxxxxxxxxxxxxxx33">>}]
```
On github side, I filled out the form field "Authorization callback URL" with https://MY ONEZONE URL/validate_login

Any idea?

Configuration:
Centos 7.5
Using Docker

**Comment by lopiola** [comment]
Can you paste the URL you are on? Should look like this: 
https://github.com/login?client_id=4c3e607521b683968153&return_to=...

**Comment by lopiola** [comment]
Anyway, it is important that you set the zone domain to your actual domain that you registered in github. When you use docker-compose + batch mode, it is set depending on ONEZONE_CONFIG -> onezone -> domainName. If you are installing via onepanel GUI, you provide your domain in the form during the first step.

**Comment by bertrandrigaud** [comment]
That's it!
On github it was https://MY_HOST/validate_login whereas domainName on docker-compose file was MY_HOST.MY_DOMAIN
I also tested with https://IP/validate_login on github and domainName: "IP" on docker-compose. 

It all works well.

Many Thanks!

**Comment by lopiola** [comment]
Glad to help :)
