### ISSUE TITLE
Canceling a scheduled or active transfer

### ISSUE THREAD

**Issue by bertrandrigaud** [onedata/onedata#25]
For unknown reasons, I've got transfers stucked. I can see them in the transfer web UI. Is there a way to cancel them? Or a trigger to force the queue to be activated?

I'm running on version 18.02.0-rc8

**Comment by luman75** [comment]
@bertrandrigaud we have noticed this problem recently, it was already fixed and be released in version 18.02.00-rc11 next week.

**Comment by bertrandrigaud** [comment]
Ok, Thanks!
