### ISSUE TITLE
How can I retrieve a file via REST API?

### ISSUE THREAD

**Issue by gillardoLapp** [onedata/onedata#26]
Hi,

I would like to retrieve the following file SPACE-CTA/test.txt using a REST client.
Which API should I call?

Thank you,

Frederic

**Comment by gillardoLapp** [comment]
Hi,
According to the documentation, the CDMI interface should do the job.
For example, according to the documentation, the following REST query should retrieve the file path, but it is not working, the server does not send any response(no error code, nothing). Moreover, there is no information in the log. 

https://lapp-xdc01.in2p3.fr/cdmi/cdmi_objectid/000000000046A99967756964236238303232333134376134386438353435346662383466313265623630633463233961353537393862363233643666346261346231383365343137633632666137

**Comment by gillardoLapp** [comment]
After investigation:
It does not work with POSTMAN as a rest client, but it works with Curl:
curl -X GET -k  https://lapp-xdc01.in2p3.fr/cdmi/cdmi_objectid/00000000004695CD677569642365333862663735626331326334613535633337336331396639643863233961353537393862363233643666346261346231383365343137633632666137 -H 'Content-Type: application/cdmi_object' -H 'X-Auth-Token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgYWVmYjJlYzNjYTQyNzk00NDVlYzAxMzk2MGU1ZjA00NmUKMDAxYWNpZCB00aW1lIDwgMTU2NzU4Mjg4MQowMDJmc2lnbmF00dXJlIOsAEmKzdR3jXi01J78MLVwYcRSvbtrwo02OtKYXn02e00HcCg' -H 'X-CDMI-Specification-Version: 1.1.1'
{"valuetransferencoding":"base64","valuerange":"0-967","parentURI":"/SPACE-SMALL/","parentID":"00000000004C8E02677569642373706163655F3961353537393862363233643666346261346231383365343137633632666137233961353537393862363233643666346261346231383365343137633632666137","objectType":"application/cdmi-object","objectName":"ubuntuConfig.txt","objectID":"00000000004695CD67756964236465336265333862663735626331326334613535633337336331396639643863233961353537393862363233643666346261346231383365343137633632666137","mimetype":"application/octet-stream","metadata":{"cdmi_size":"968","cdmi_owner":"b3fb1e96153974ef97dba0bea310804b","cdmi_mtime":"2018-10-24T14:35:32Z","cdmi_ctime":"2018-10-24T14:35:32Z","cdmi_atime":"2018-10-24T14:39:11Z"},"completionStatus":"Complete","capabilitiesURI":"cdmi_capabilities/dataobject/","value":"c3VkbyBhcHQtZ2V0IHVwZGF0ZQ0Kc3VkbyBhcHQtZ2V0IGluc3RhbGwgZmlyZWZveA0Kdmkgfi8uYmFzaHJjDQpleHBvcnQgRElTUExBWT0xMjcuMC4wLjE6MA0KZXhwb3J0IERPQ0tFUl9IT1NUPSd0Y3A6Ly8wLjAuMC4wOjIzNzUnDQoNCiNkb2NrZXINCnN1ZG8gYXB0LWdldCB1cGRhdGUNCnN1ZG8gYXB0LWdldCBpbnN0YWxsICBhcHQtdHJhbnNwb3J0LWh0dHBzIA0Kc3VkbyBhcHQtZ2V0IGluc3RhbGwgIGNhLWNlcnRpZmljYXRlcw0Kc3VkbyBhcHQtZ2V0IGluc3RhbGwgIGN1cmwgDQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAgc29mdHdhcmUtcHJvcGVydGllcy1jb21tb24NCmN1cmwgLWZzU0wgaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L3VidW50dS9ncGcgfCBzdWRvIGFwdC1rZXkgYWRkIC0NCnN1ZG8gYWRkLWFwdC1yZXBvc2l0b3J5ICJkZWIgW2FyY2g9YW1kNjRdIGh0dHBzOi8vZG93bmxvYWQuZG9ja2VyLmNvbS9saW51eC91YnVudHUgJChsc2JfcmVsZWFzZSAtY3MpIHN0YWJsZSINCnN1ZG8gYXB0LWdldCB1cGRhdGUNCnN1ZG8gYXB0LWdldCBpbnN0YWxsIGRvY2tlci1jZQ0KZG9ja2VyIHBzIC1hDQoNCg0Kc3VkbyBjdXJsIC1MIGh0dHBzOi8vZ2l0aHViLmNvbS9kb2NrZXIvY29tcG9zZS9yZWxlYXNlcy9kb3dubG9hZC8xLjIwLjEvZG9ja2VyLWNvbXBvc2UtYHVuYW1lIC1zYC1gdW5hbWUgLW1gIC1vIC91c3IvbG9jYWwvYmluL2RvY2tlci1jb21wb3NlDQpzdWRvIGNobW9kICt4IC91c3IvbG9jYWwvYmluL2RvY2tlci1jb21wb3NlDQoNCmRvY2tlci1jb21wb3NlIC0tdmVyc2lvbg0KDQoNCg0KI2xlIHJlc3RlDQpzdWRvIGFwdC1nZXQgaW5zdGFsbCBmaXJlZm94DQpkb3dubG9hZCBhbmFjb25kYQ0KYmFzaCB+L0Rvd25sb2Fkcy9BbmFjb25kYTMtNS4xLjAtTGludXgteDg2XzY0LnNoDQpkb3dubG9hZCBJbnRlbGxpag0KdGFyIC14emYgaWRlYS0yMDE4LjEudGFyLmd6DQo="}

**Comment by groundnuty** [comment]
First that's how you list all the files in a space:

```bash
curl  -sS --tlsv1.2 -v -H "X-Auth-Token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNGYxZWQxOTlhMzdmNTEwM2NiYTA1YzZhYTAyOTRmODUKMDAxYWNpZCB00aW1lIDwgMTU3MTc3NDMyOQowMDJmc2lnbmF00dXJlIJtAfU3jpmJSvKuNALM4q3UKoXwQtmE00Bx00IAjQJqgRiCg"  -X GET "https://release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to/api/v3/oneprovider/files/krk-3/"

*   Trying 10.32.16.115...
* TCP_NODELAY set
* Connected to release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to (10.32.16.115) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=10-32-16-115.release18020-rc11.pod.dev.onedata.uk.to
*  start date: Oct 22 15:46:00 2018 GMT
*  expire date: Oct 22 15:46:00 2019 GMT
*  issuer: CN=kubernetes
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET /api/v3/oneprovider/files/krk-3/ HTTP/1.1
> Host: release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to
> User-Agent: curl/7.61.1
> Accept: */*
> X-Auth-Token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNGYxZWQxOTlhMzdmNTEwM2NiYTA1YzZhYTAyOTRmODUKMDAxYWNpZCB00aW1lIDwgMTU3MTc3NDMyOQowMDJmc2lnbmF00dXJlIJtAfU3jpmJSvKuNALM4q3UKoXwQtmE00Bx00IAjQJqgRiCg
>
< HTTP/1.1 200 OK
< content-length: 394
< content-type: application/json
< date: Fri, 26 Oct 2018 10:32:23 GMT
< server: Cowboy
< x-frame-options: SAMEORIGIN
<
* Connection #0 to host release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to left intact
[{"path":"/krk-3/h.sh","id":"0000000000462C8767756964233338666337626234306234323835326263356331316337643639653864313561233462373261616636316635336530383639353134373838373838383834393435"},{"path":"/krk-3/onedata-devel-openrc.sh","id":"000000000046061A67756964236336353966383332643262323932333832613730336563656238396165313536233462373261616636316635336530383639353134373838373838383834393435"}]%
``` 

Now you can query a file by either id or filename. I will show the filename option since, when downloading a file, curl will save using it's filename instead of its id.

```bash
curl -O -ksS --tlsv1.2 -vv -H "X-Auth-Token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNGYxZWQxOTlhMzdmNTEwM2NiYTA1YzZhYTAyOTRmODUKMDAxYWNpZCB00aW1lIDwgMTU3MTc3NDMyOQowMDJmc2lnbmF00dXJlIJtAfU3jpmJSvKuNALM4q3UKoXwQtmE00Bx00IAjQJqgRiCg"  -X GET "https://release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to/cdmi/krk-3/onedata-devel-openrc.sh"

*   Trying 10.32.16.115...
* TCP_NODELAY set
* Connected to release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to (10.32.16.115) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1752 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [205 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=10-32-16-115.release18020-rc11.pod.dev.onedata.uk.to
*  start date: Oct 22 15:46:00 2018 GMT
*  expire date: Oct 22 15:46:00 2019 GMT
*  issuer: CN=kubernetes
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
} [5 bytes data]
> GET /cdmi/krk-3/onedata-devel-openrc.sh HTTP/1.1
> Host: release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to
> User-Agent: curl/7.61.1
> Accept: */*
> X-Auth-Token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNGYxZWQxOTlhMzdmNTEwM2NiYTA1YzZhYTAyOTRmODUKMDAxYWNpZCB00aW1lIDwgMTU3MTc3NDMyOQowMDJmc2lnbmF00dXJlIJtAfU3jpmJSvKuNALM4q3UKoXwQtmE00Bx00IAjQJqgRiCg
>
{ [5 bytes data]
< HTTP/1.1 200 OK
< content-length: 1802
< content-type: application/octet-stream
< date: Mon, 29 Oct 2018 10:11:30 GMT
< server: Cowboy
< transfer-encoding: chunked
< vary: accept
< x-frame-options: SAMEORIGIN
<
{ [5 bytes data]
* Connection #0 to host release18020-rc11-oneprovider-krakow.release18020-rc11.svc.dev.onedata.uk.to left intact

 orzech@orzechpro-2> ls
onedata-devel-openrc.sh

```
