### ISSUE TITLE
Can not upload file in a given space

### ISSUE THREAD

**Issue by gillardoLapp** [onedata/onedata#27]
When uploading a file in a given space, I have the following error in the provider log:

[D 2018-10-24 14:34:45.619 <0.20890.313>] Supervisor {<0.20890.313>,session_sup} started event_manager_sup:start_link(<<"6caf085ceff1cf43ec6e9cd2d4704673">>) at pid <0.20963.313>
[op_worker] [E 2018-10-24 14:46:36.987 <0.25498.313>] Error while streaming file upload from user <<"b3fb1e96153974ef97dba0bea310804b">> - error:{badmatch,
[op_worker]                                                                                             {error,
[op_worker]                                                                                              enospc}}
[op_worker] Stacktrace:
[op_worker]     proc_lib:init_p_do_apply/3 line 247
[op_worker]     cowboy_stream_h:request_process/3 line 227
[op_worker]     cowboy_stream_h:execute/3 line 249
[op_worker]     cowboy_handler:execute/2 line 37
[op_worker]     dynamic_page_handler:init/2 line 37
[op_worker]     page_file_upload:handle/2 line 57
[op_worker]     page_file_upload:multipart/3 line 221
[op_worker]     page_file_upload:stream_file/4 line 249

There is no error in the log from onezone, and if a create a new space on the same provider everything works fine on the new space.

Thanks,

Frederic

**Comment by groundnuty** [comment]
We need oneprovider version to say anything...

**Comment by lopiola** [comment]
Looks like there was no space left on your storage device: `[op_worker] {error, enospc}}`.
Please keep in mind that you must properly configure the storage quota according to the actual storage capacity. Our quota mechanism depend on the assigned support size in space settings. If it was configured, you would get a proper error on the client side.
