### ISSUE TITLE
SSL_ERROR_HANDSHAKE_FAILURE_ALERT problem with Mozilla Firefox (v50.0)

### ISSUE THREAD

**Issue by glarocca** [onedata/onedata#3]
Hi all,
I am not able to access the Oneprovider [1] using the latest version of Mozilla Firefox. 
Thank you.
Cheers, Giuseppe

[1] https://147.228.242.126:9443/

**Comment by groundnuty** [comment]
@glarocca we tested it, and so far it seems to work, if you see any problems please reopen it.
