### ISSUE TITLE
Handshake error: incompatible Oneprovider version

### ISSUE THREAD

**Issue by gmolto** [onedata/onedata#36]
Hi,

Installing the oneclient through the usual installation approach:
```
curl -sS  http://get.onedata.org/oneclient.sh | bash
````
currently installs oneclient version 18.02.3. However, the plg-cyfronet-01 oneprovider (in EGI DataHub) has oneprovider version 18.02.1. Therefore attempting to mount the Onedata space results in an "incompatible Oneprovider version" error:

```
Connecting to provider 'plg-cyfronet-01.OMITTED' using session ID: '15240073247038925449'...
E0912 15:21:17.000768 23797 configuration.cc:41] Fatal error during handshake: incompatible Oneprovider version
E0912 15:21:17.001421 23797 clprotoHandshakeResponseHandler.h:49] Error during handshake: handshake:10
E0912 15:21:17.001543 23797 translator.h:95] **Handshake error: incompatible Oneprovider version(10)**
E0912 15:21:17.002769 23797 clprotoClientBootstrap.cc:225] Connection refused by remote Oneprovider at plg-cyfronet-01.datahub.egi.eu:443: std::runtime_error: Error during handshake.
Connection refused - aborting...
```
How can I choose to install a specific version of the oneclient through the installation script to overcome this problem? 

Thanks in advance.

**Comment by gmolto** [comment]
For the sake of completeness, this problems was solved by taking the specific version of the RPM package from http://onedata-dev-packages.cloud.plgrid.pl/yum/centos/7x/x86_64/ and transforming it into a DEB package. Still, I would like to know if there is a better approach to install a specific version of the oneclient.

**Comment by groundnuty** [comment]
Hello!
I'm aware of the issue that the installation script always takes the newest release version of the current major release (18.* int hat case). It's tempting to ask a user to pass as a first argument the URL of the oneprovider he will want to connect to. Then the script could install the same version as  listed returned by this endpoint: [https://datahub.egi.eu/configuration].(https://datahub.egi.eu/configuration)

Unfortunately, it's not always a case that the oneprovider that user will want to connect is even deployed/running/known before starting oneclient deployment. 
There is an undocumented way to install a specific version of oneclient using this script, this line demonstrates the usage: https://github.com/onedata/oneclient/blob/develop/docker/Dockerfile#L43
just pass as a first argument what you would pass to apt-get/yum etc to install a specific version of a package using respected package managers. In case of the apt case:

- you can use `apt policy oneclient` (after running a script at least once so it adds our repo to our system first)
- or you can take a version of the package from here: [http://onedata-dev-packages.cloud.plgrid.pl/apt/ubuntu/1802/pool/main/o/oneclient/](http://onedata-dev-packages.cloud.plgrid.pl/apt/ubuntu/1802/pool/main/o/oneclient/)
- then (example) you pass to the installation script argument `oneclient=18.02.2-1~xenial` as you would pass it to the apt: `apt install oneclient=18.02.2-1~xenial`

Hope that helps!

**Comment by gmolto** [comment]
Thanks for the detailed response!
