### ISSUE TITLE
Unable to get groups and roles from delegated credentials through EGI Check-in

### ISSUE THREAD

**Issue by AJRubio-Montero** [onedata/onedata#37]
Good evening.

(This issue corresponds to the code included in the oz-worker' repository, but it laks the usability of whole OneData service).

The custom parser that implements groups for the EGI Check-in IdP (https://aai.egi.eu) doesn't take into consideration groups from delegated credentials. This problem can be checked at https://datahub.egi.eu.

For example, I can login into https://datahub.egi.eu with my eduTEAMs credential passing through EGI Check-in (https://aai.egi.eu). Then, https://datahub.egi.eu obtains an "eduperson_entitlement" similar to this (for my LAGO-AAI virtual organisation):

urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI#eduteams.org

However, the function “parse_egi_entitlement”, at line 104 in (https://github.com/onedata/oz-worker/blob/05a6aca6a171df9767613368c15e4a9ddc2eeca4/rel/files/auth_plugins/custom_entitlement_parser.erl), only accepts URNs starting by "urn:mace:egi.eu:group:”, so any group from eduTEAMS or any other delegated IdP will be ignored.

I think you should consider to allow any NAMESPACE after "urn:" and before ":group:".

--

Another issue is how the permissions are set. Following the AARC-G002 recommedations (https://aarc-project.eu/wp-content/uploads/2017/11/AARC-JRA1.4A-201710.pdf), any entitlement declaring a group should imply to grant user permissions at least as "member". 

Additionally, the ROLE component is optional in AARC-G002. This issue has been traditionally  solved taking the last SUBGROUP as the role of the preceding group. For example, for the "manager" role:

urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:manager#eduteams.org

Nevertheless, although EGI also follows AARC recommendations, I know it is introducing ROLE component as a must (https://wiki.egi.eu/wiki/AAI_guide_for_SPs). In consequence, I have not suggestions to solve the issue, but it involves compatiblity.

Thank you very much in advance.
Cheers.

**Comment by lopiola** [comment]
Hello,

the current parser indeed accepts only entitlements with the EGI namespace. It has been implemented according to the specification from: https://wiki.egi.eu/wiki/AAI_guide_for_SPs - where the entitlement syntax is defined as:

`urn:mace:egi.eu:group:<GROUP>[:<SUBGROUP>*]][:role=<ROLE>]#<GROUP-AUTHORITY>`

The prefix is fixed, so we do not expect (or accept) any other namespaces. If you think this behaviour should be revised, we first need to run this by the EGI. Do you have access to their helpdesk (https://ggus.eu)? If so, please create an issue there and we will reimplement the parser when there is such decision on their side. 

---

> "any entitlement declaring a group should imply to grant user permissions at least as "member"

The parser defaults to "member" role, this is the lowest you can get. I think it satisfies the requirement?

> Nevertheless, although EGI also follows AARC recommendations, I know it is introducing ROLE component as a must (https://wiki.egi.eu/wiki/AAI_guide_for_SPs). In consequence, I have not suggestions to solve the issue, but it involves compatiblity.

I see the problem, again we would have to talk to the EGI Check-in guys as they would need to revise the syntax.

Cheers,
Lukasz Opiola

**Comment by AJRubio-Montero** [comment]
Hello Lukasz,

OK, I will open a ticket at ggus, but I understand that a possible duplicity of group names is the actual problem, i.e. the same VO group in different NAMESPACES. For example:

urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI#eduteams.org
urn:mace:egi.eu:group:LAGO-AAI#aai.egi.eu

Am I wrong?

Thanks.
Cheers.

**Comment by lopiola** [comment]
Great, thank you.

It depends how we decide to map the NAMESPACEs into VOs. If all of them fall into the same VO, then yes, those two groups will be indistinguishable. We could also map each NAMESPACE to different VO, then the structure could look like this:
```
|--EGI
|   |--LAGO-AAI
|
|--Geant
     |--LAGO-AAI
```
and they would be treated as two different groups. In Onedata you can have any number of nested groups, and there is no problem to have VO groups on two levels (LAGO-AAI being a "sub-VO" group).

Cheers,
Lukasz Opiola

**Comment by marcvs** [comment]
The spec you are talking about is this one:
https://aarc-project.eu/guidelines/aarc-g002/
From the example above: these are two different groups! Linking two different groups is not specified. Do you have that use case in LAGO?

**Comment by AJRubio-Montero** [comment]
Hello Marcus.

> From the example above: these are two different groups! Linking two different groups is not specified. 
> Do you have that use case in LAGO?"

No, we haven't.  However, if someone register a group with the same name, we have a problem if both groups hang from the EGI voGroupName (see below).

Actually they should be two different groups, because each group should be managed by different organizations. Thus, my initial proposed solution  (_to allow any NAMESPACE after "urn:" and before ":group:"."_ ) is wrong and it is not covered by the AARC spec.

Therefore, the idea should be:

|--EGI
|   |--LAGO-AAI  (it can exists or not, this is not my group and it should not be my problem).
|
|--geant:eduteams.org  (or some similar name, GEANT could have other IdPs than eduteam)
|   |--LAGO-AAI  (my group, managed by me)


As commented Lukasz: "we could also map each NAMESPACE to different VO". However, the concept of VO in OneData is not exactly the same as the usual in EGI. 

For OneData, a VO is the EGI itself, and it is associated to one IdP configuration. See the statement (_voGroupName => "EGI"_) at: https://onedata.org/docs/doc/administering_onedata/openid_saml_configuration/openid_saml_configuration_19_02.html#egi-config-openid-connect

You could enable the eduTeams IdP with its own configuration in OneData, but then, the autorisation will not be managed through EGI Check-in, hindering compatibility with other IdPs (and perhaps the centrallised accounting in EGI).

I don't know if there are other mechanisms for easily implement this issue.


Thanks you very much.
Cheers.

**Comment by lopiola** [comment]
@AJRubio-Montero the `voGroupName` is optional. If it is set like in the example (and, in fact, in DataHub right now) - then you are right, all the groups will hang from the top EGI VO group. 

You can unset the `voGroupName`, and then the group structure will be exactly what the entitlement parser returns, without being attached to the special top level VO group. Then, you can return different VOs as parsing results of different entitlements. 

VO in Onedata is just a group type that does not carry any additional meaning, it's there just for better depiction of structures in IdPs. For example, this is allowed:

```
|--EGI  (VO) 
|     |--LAGO-AAI  (VO)
|            |--STAFF  (unit)
|                  |--ADMINS  (team)
|
|--geant:eduteams.org (VO) 
      |--LAGO-AAI  (VO)
             |--STAFF  (unit)
                   |--ADMINS  (team)
```

**Comment by AJRubio-Montero** [comment]
Hello again.
> You can unset the voGroupName, and then the group structure will be exactly what the entitlement parser returns,

Can it straightforwardly unset voGroupName in DataHub? Will permissions, dataset paths, PIDs and metadata of EGI groups maintained? If it is so, it is perfect.

**Comment by lopiola** [comment]
> Can it straightforwardly unset voGroupName in DataHub? Will permissions, dataset paths, PIDs and metadata of EGI groups maintained? If it is so, it is perfect.

Yes, but only if you ensure that groups coming from EGI will be mapped to exact same structure. It can be achieved - if we remove the `voGroupName` and add the "EGI" VO (with the same name) on the parser level as parent of each group from EGI, their structure will be exactly the same.

**Comment by NicolasLiampotis** [comment]
Hello. I would like to point out that Check-in will be configured to map group information under the GÉANT eduTEAMS namespace (`urn:geant:eduteams.org:service:eduteams:group:`) to the EGI namespace (`urn:mace:egi.eu:group:`) with the required role information. So it won't be necessary for DataHub to handle entitlements under different namespaces. 

@lopiola Please let me know if you see any issues with this approach

**Comment by lopiola** [comment]
Hello @NicolasLiampotis. If I understand correctly, we wouldn't have to take any action on the Onedata side. When you implement the mapping to your namespace the GÉANT groups will be picked up by Onedata. If so, I don't see any issues here.

**Comment by AJRubio-Montero** [comment]
Hello @NicolasLiampotis 

If you map these namespaces, we could find a duplicity in groups names in the future. 

Perhaps, you could map to a special subgroup in EGI (urn:mace:egi.eu:group:**eduteams**:).  It seems safer and simpler than configure OneData.

On the other hand, datahub.egi.eu is down. Is it because are you testing this configuration?.

Cheers

**Comment by lopiola** [comment]
There is a general cloud malfunction in Cyfronet where DataHub is deployed - the admins are doing what they can to bring the services back.

**Comment by NicolasLiampotis** [comment]
> If I understand correctly, we wouldn't have to take any action on the Onedata side. When you implement the mapping to your namespace the GÉANT groups will be picked up by Onedata. If so, I don't see any issues here.

The mapping has been implemented in Check-in as follows:
`urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI(*)#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net(*):role=member#aai.egi.eu`

For example the following entitlements would be mapped as follows:

1. `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:role=member#aai.egi.eu`
2. `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:manager#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:manager:role=member#aai.egi.eu `
2. `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:parent:child#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:parent:child:role=member#aai.egi.eu`

Effectively, any group hierarchy from the geant namespace will be mapped under the egi namespace so no changes should be required on the Onedata side.

**Comment by lopiola** [comment]
Great, is this already in production? If so, maybe somebody having GÉANT entitlements could log in and confirm that everything works as expected (@AJRubio-Montero ?)

**Comment by NicolasLiampotis** [comment]
Hello @lopiola,

Yes, the mapping is already implemented in production with some modifications based on @AJRubio-Montero 's feedback:

General rule:
-  `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:parent:child#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:manager:parent:child:role=member#aai.egi.eu`

where child group doesn't match `manager` or `owner`.

Specific rules:
1. `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:parent:child:manager#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:parent:child:role=manager#aai.egi.eu`
2. `urn:geant:eduteams.org:service:eduteams:group:LAGO-AAI:parent:child:owner#eduteams.org` --> `urn:mace:egi.eu:group:lagoproject.net:parent:child:role=owner#aai.egi.eu`

**Comment by lopiola** [comment]
Okay, thank you

**Comment by AJRubio-Montero** [comment]
Hello,

I confirm that all works fine with the mappings introduced by @NicolasLiampotis

Thank you very much for the support.
Cheers.
