### ISSUE TITLE
Oneclient 20.02.x for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by andrea-manzi** [onedata/onedata#38]
Hello,
would it be possible to have a package for Ubuntu 20.04 for the oneclient 19.02.x release?

i'm getting this error when i try to install it

  Either your platform is not easily detectable, is not supported by this
  installer script, or does not yet have a package for oneclient.
  Currently supported distributions are: ubuntu trusty, ubuntu wily, ubuntu xenial, centos 7 and fedora 23

thanks
Andrea

**Comment by bkryza** [comment]
@andrea-manzi yes, we're planning to support Ubuntu Focal soon but probably not earlier than in 2 weeks (we need to create  a new repository in our package server and integrate it with our CI...)

However, the oneclient packages are pretty much self-contained, i.e. you should be able to install the Bionic package manually on Focal without any issues - like this:

```
wget http://packages.onedata.org/apt/ubuntu/1902/pool/main/o/oneclient/oneclient_19.02.3-1~bionic_amd64.deb
apt-get install ./oneclient_19.02.3-1~bionic_amd64.deb
```

Cheers,
Bartosz

**Comment by andrea-manzi** [comment]
Hi Bartosz, 
thanks the package for bionic works fine also on Focal 
cheers
Andrea

**Comment by thebe14** [comment]
This should install on standard Ubuntu 20.04 LTS out of the box. Or just replace the official docs with instructions from this ticket.

**Comment by andrea-manzi** [comment]
Hi @bkryza 
i'm reopening this one, to understand what are your plan to support Ubuntu Focal installation
thanks
Andrea

**Comment by bkryza** [comment]
@andrea-manzi Focal channel has been added to our distribution set for `oneclient`, so this works now on `focal` directly:

```bash
curl -sS  http://get.onedata.org/oneclient.sh | bash
```

**Comment by sebastian-luna-valero** [comment]
Indeed, I confirm it works, many thanks!

**Comment by andrea-manzi** [comment]
thanks a lot @bkryza closing this
