### ISSUE TITLE
Continue getting a partially-downloaded file through CDMI interface

### ISSUE THREAD

**Issue by AJRubio-Montero** [onedata/onedata#39]
Good Morning.

(I apologize if this question is not an issue or it is at the wrong repository)

We have noted that we cannot recovery partially-downloaded files when we are using the CDMI interface. This is a problem for big files, specially for remote users located at the other side of Atlantic Ocean, where micro-cuts are usual.

We tested `curl -C-` and `wget -c`. For example:

`curl -O -C- -k -H "X-Auth-Token: MDA...go"  "https://mon01-tic.ciemat.es/cdmi/test4/file.tar.gz"`
`** Resuming transfer from byte position 8093688`
` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current `
`  0  148M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0 `
**`curl:** (33) HTTP server doesn't seem to support byte ranges. Cannot resume.`**

` wget -c -d --header="X-Auth-Token: MDA...go"  https://mon01-tic.ciemat.es/cdmi/test4/test4/file.tar.gz`
`...`
`...`
`file.tar.gz   4%[>                                  ]   7,11M   237KB/s    in 32s    `
`2020-09-17 14:34:51 (228 KB/s) - Connection closed at byte 7454712. Retrying.`

However,  HTTP range reads should work in [19.02 release](https://onedata.org/#/home/documentation/19.02/doc/advanced/cdmi.html) , but if I try some examples as the one described in the documentation:

`curl -k -H "X-Auth-Token: MDA...go" -H 'Range: 0-3' -X GET "https://mon01-tic.ciemat.es/cdmi/test4/file.tar.gz"`

I always obtain as the contain of downladed file (or sometimes as output):

**`{"error":"Bad value: provided \"range\" could not be understood by the server"}`**

The OneProvider that we are using is *mon01-tic.ciemat.es* with the 19.02.3 release, registered in *datahub.egi.eu*.

Thanks in advance.
Cheers.

**Comment by lopiola** [comment]
Hello,
this is the right repo :) Thank you for the report, we have investigated and found out that:

1. Indeed we do not properly support downloading partial files (some headers are missing server-side), we will fix that in the next release.

2. There is an error in the docs, a working example should look like this:
`curl -k -H $TOKEN_HEADER -H 'Range: bytes=0-3' -X GET "$ENDPOINT/test/test.txt"`
(the `bytes=` is missing) - we will fix the docs shortly. Let me know if that works for you.

Cheers

**Comment by AJRubio-Montero** [comment]
Hello @lopiola

>`curl -k -H $TOKEN_HEADER -H 'Range: bytes=0-3' -X GET "$ENDPOINT/test/test.txt"`
>(the bytes= is missing) - we will fix the docs shortly. Let me know if that works for you.

This doesn't return error, but the ouput is not in the range specified.  We will wait the fix in the next release. 

Thank you very much!.
Cheers.

**Comment by lopiola** [comment]
> but the ouput is not in the range specified

Hmm, are you sure? I've just tested (see below) and the range works as it should. Can you give me details - what output are you getting?

I've got a file, with content = `Test\n`, and here is the output of the command:
```
curl -k -H $TOKEN_HEADER -H 'Range: bytes=0-1' -X GET "$ENDPOINT/Demo%20Space/hello.txt"
Te
```

**Comment by AJRubio-Montero** [comment]
Hello. 

This is my output of a file that repeats the abecedary every line:

```
# curl -k -H "X-Auth-Token: MDA...go" -H 'Content-Type: application/cdmi-object' -H 'Range bytes=0-1'  -X GET  "https://mon01-tic.ciemat.es/cdmi/test4/test/ABC.txt"
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
ABCDEFGHIJKLMNOPQRSTUVWXYZ
```

**Comment by lopiola** [comment]
Hello,

you forgot the colon `:` after the `Range` header; `Range` is the header name and `bytes=0-1` is the value.
Also, the `Content-Type` header does not make sense in this request (you are not posting any data, but fetching it).

Please Try this:
```
curl -k -H "X-Auth-Token: MDA...go" -H 'Range: bytes=0-1'  -X GET  "https://mon01-tic.ciemat.es/cdmi/test4/test/ABC.txt"
```

**Comment by AJRubio-Montero** [comment]
Sorry for the mistake.  It works, also with `Content-Type` and selecting intermediate bytes:

`curl -k -H "X-Auth-Token: MDA...go" -H 'Content-Type: application/cdmi-object' -H 'Range: bytes=2-3' "https://mon01-tic.ciemat.es/cdmi/test4/test/ABC.txt"`
`CD`

Thank you very much.

**Comment by lopiola** [comment]
Full support for resuming partial downloads has been added in versions `19.02.5` and `20.02.3`.
