### ISSUE TITLE
Installation 2_0_oneprovider_onezone

### ISSUE THREAD

**Issue by luda171** [onedata/onedata#4]
Hi,
I downloaded getting started scenario 2_0_oneprovider_onezone.  Attempt to start  ./run_onedata.sh --zone fails with  * service_couchbase: start
onezone-1                  | 
onezone-1                  | Error: Service Error
onezone-1                  | Description: Action 'deploy' for a service 'onezone' terminated with an error.

as root user.
in oz_panel error log I have:
  more error.log 
2017-01-11 21:12:19.130 [error] <0.481.0>@service_utils:log:226 Step service_couchbase:start failed
Node: 'onepanel@node1.onezone.localhost'
Reason: badarg
Stacktrace: [{erlang,list_to_integer,
                     ["/bin/sh: 1: ulimit: error setting limit (Operation not permitted)\n0"],
                     []},
             {onepanel_shell,call,1,
                             [{file,"/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_shell.erl"},
                              {line,91}]},
             {onepanel_shell,check_call,1,
                             [{file,"/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_shell.erl"},
                              {line,101}]},
             {onepanel_rpc,apply,3,
                           [{file,"/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_rpc.erl"},
                            {line,41}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,187}]}]
2017-01-11 21:12:19.131 [error] <0.481.0>@service_utils:log:216 Action onezone:deploy failed due to: {service_couchbase,start,
                                      {[],
                                       [{'onepanel@node1.onezone.localhost',
                                         {error,onepanel_rpc,apply,3,
                                          undefined,badarg,
                                          [{erlang,list_to_integer,
                                            ["/bin/sh: 1: ulimit: error setting limit (Operation not permitted)\n0"],
                                            []},
                                           {onepanel_shell,call,1,
                                            [{file,
                                              "/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_shell.erl"},
                                             {line,91}]},
                                           {onepanel_shell,check_call,1,
                                            [{file,
                                              "/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_shell.erl"},
                                             {line,101}]},
                                           {onepanel_rpc,apply,3,
                                            [{file,
                                              "/build/oz-panel-AEwFIY/oz-panel-3.0.0.rc11/_build/package/lib/onepanel/src/modules/onepanel_rpc.erl"},
                                             {line,41}]},
                                           {rpc,'-handle_call_call/6-fun-0-',
                                            5,
                                            [{file,"rpc.erl"},{line,187}]}],
                                          43}}]}}
2017-01-11 21:12:20.863 [error] <0.510.0>@onepanel_errors:translate:139 Function: onepanel_rpc:apply/3
Args: undefined
Reason: badarg
....
Any  ideas what can cause it?

**Comment by colakong** [comment]
@luda171 I also had issues until using newer versions of the containers from the [sixth release of Indigo-1](https://indigo-dc.gitbooks.io/indigo-datacloud-releases/content/indigo1/sixth_update_of_indigo-1.html)
```
diff --git a/scenarios/2_0_oneprovider_onezone/docker-compose-oneclient.yml b/scenarios/2_0_oneprovider_onezone/docker-compose-oneclient.yml
index 2bcd592..cdf3c22 100644
--- a/scenarios/2_0_oneprovider_onezone/docker-compose-oneclient.yml
+++ b/scenarios/2_0_oneprovider_onezone/docker-compose-oneclient.yml
@@ -2,7 +2,7 @@ version: '2.0'
 
 services:
   oneclient:
-    image: onedata/oneclient:3.0.0-rc11
+    image: indigodatacloud/oneclient:indigo_1
     privileged: true
     # dns: 8.8.8.8 # uncomment if container can't ping any domain
     container_name: oneclient-1
diff --git a/scenarios/2_0_oneprovider_onezone/docker-compose-oneprovider.yml b/scenarios/2_0_oneprovider_onezone/docker-compose-oneprovider.yml
index b3d1cb8..082b9ba 100644
--- a/scenarios/2_0_oneprovider_onezone/docker-compose-oneprovider.yml
+++ b/scenarios/2_0_oneprovider_onezone/docker-compose-oneprovider.yml
@@ -2,7 +2,7 @@ version: '2.0'
 
 services:
   node1.oneprovider.localhost:
-    image: onedata/oneprovider:3.0.0-rc11
+    image: indigodatacloud/oneprovider:indigo_1
     hostname: node1.oneprovider.localhost
     # dns: 8.8.8.8 # uncomment if container can't ping any domain
     container_name: oneprovider-1
diff --git a/scenarios/2_0_oneprovider_onezone/docker-compose-onezone.yml b/scenarios/2_0_oneprovider_onezone/docker-compose-onezone.yml
index b7be31f..836e54a 100644
--- a/scenarios/2_0_oneprovider_onezone/docker-compose-onezone.yml
+++ b/scenarios/2_0_oneprovider_onezone/docker-compose-onezone.yml
@@ -2,7 +2,7 @@ version: '2.0'
 
 services:
   node1.onezone.localhost:
-    image: onedata/onezone:3.0.0-rc11
+    image: indigodatacloud/onezone:indigo_1
     hostname: node1.onezone.localhost
     # dns: 8.8.8.8 # uncomment if container can't ping any domain
     container_name: onezone-1
```
After switching the container images it worked fine.

**Comment by groundnuty** [comment]
@colakong thank you for pointing out the possible problem. However the indigodatacloud/onezone:indigo_1 is just retagged onedata/onezone:3.0.0-rc11. They are exacly the same. Indigo-1 Update 6 == onedata RC11.

@luda171 I assume you are ussing master branch, with unchanged compose files?

**Comment by luda171** [comment]
yes, I downloaded today as git clone https://github.com/onedata/getting-started and I did not change files, It has  (onedata/onezone:3.0.0-rc11) image in compose files.

**Comment by groundnuty** [comment]
@luda171 that is quite strange, on what type of VM are you running it? how many vcpu-s and ram?

**Comment by luda171** [comment]
we are running 2 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz vcpus, with 16G of ram.
we have shared VM in AWS, we are using VMs in a shared hardware. Virtualization type is hvm

**Comment by groundnuty** [comment]
ok, please send us the content of a folder 'config_onezone' which you will find in a scenario 2.0 directory after a failed (or successful) run. My first bet here is something to do with hardware - couchbase can be quite picky.

**Comment by luda171** [comment]
I attached the content of config directory.​
 confonezone.tar
<https://drive.google.com/file/d/0B2zvrgX7AKCUY3NmeEtHSWZJdE0/view?usp=drive_web>
​

**Comment by groundnuty** [comment]
got it:
https://github.com/lifegadget/docker-couchbase#prerequisites
That's the error that is reported in the logs. In this link they provide a possible solution. I have no way to reproduce it on my end so please try it. 
What os and docker version are you running? It's a first time we encountered this.

Michal

**Comment by luda171** [comment]
Thanks for the help,

the Docker version 1.11.2, build b9f10c9/1.11.2, and  Amazon Linux
3.14.48-33.39.amzn1.x86_64

Turned out, the  /etc/sysconfig/docker had options which overshadowed
system values.

#OPTIONS="--default-ulimit nofile=1024:4096"

OPTIONS="--default-ulimit nofile=262144:262144"
The coach db problem is now gone.

**Comment by luda171** [comment]
Hello,
How can I access web interface  onepanel  using http proxy?
I made nginx  virtual server to proxy to zone ip address

location / {

proxy_pass https://<zone ip address>;
but getting errors (see below).
how interface intended to be configured for access?
