### ISSUE TITLE
Documentation for backing up / restoring oneprovider shares

### ISSUE THREAD

**Issue by AJRubio-Montero** [onedata/onedata#40]
Good Evening. 

After I rebooting my OneProvider instance, it was unable to view the data in the configured spaces. The OneProvider panel looked fine, but the "Browse Files" link didn't appear for the users. This seems that the permissions stored were lost (Was Couchbase corrupted? it possibly was). 

As it has not been the first time that it happens, finally, I reinstalled the instance, using the 1902 repo (http://packages.onedata.org/yum/1902/centos/7x) and forcing the 19.02.3 release for cluster_manager, op_worker, op_panel and oneprovider packets. Now, it seems that I can reboot the system without problems, but I have lost the whole previous metadata (not the data, which it remains in the filesystem tree).

Therefore, I have doubts about how I can recover metadata and user permissions for every file after any kind of event (hangs, Couchbase corruptions or hardware failures of the oneprovider). I suspect both are stored in Couchbase database, but I have not found documentation about these questions. 

¿Can you please add a section with backup tips? (Specifically, with methods to rebuild metadata and permissions for every file in a disk space). 

Thank you very much in advance.
Cheers.

**Comment by lopiola** [comment]
Hello,

backups are quite straightforward when you create a dockerized deployment - it is enough to regularly backup the persistence directory, mounted on the host (see the `docker-compose.yml`). We strongly recommend using onedatify, then the persistence resides in`/opt/onedata/onedatify/oneprovider_conf` - you can get ready-to-use onedatify commands in the space support menu in Onezone. Upgrades are also straightforward - it's enough to bump the docker image and restart (preceded by a backup, of course).
https://onedata.org/#/home/documentation/stable/doc/administering_onedata/onedatify_deploy.html

We do not recommend manual installation using packages, as there is quite a lot of administrative effort and knowledge required to do this correctly. The dockerization hides all of this away from the admin. If you insist, you can see what files we keep in the persistence by consulting the below link, and back them up regularly. Most of the metadata and configuration is stored in Couchbase, but there are other important config files and Onepanel's database (mnesia) - basically all of this, apart from logs, is required for the service to run correctly.
https://github.com/onedata/onedata/blob/develop/docker/persistence-dir.py

In case of any data corruption, you should simply restore the latest uncorrupted backup. In general, it is not possible to rebuild the metadata that was stored in the database solely based on the disk contents as there is a lot more information stored in Oneprovider's database than on disk, especially those related to data distribution between different Oneproviders. If you do not have a backup, it is not possible to bring back the previous state. 

For some storages, however, it is possible to run automatic storage import. You could create a new space, create an imported storage pointing to your pre-populated disk, support the space with the Oneprovider and enable import. This will make the files visible in the space and usable, but will not bring the state from before the corruption (files will have different uuids etc). 

You are right that we should add a section in documentation with a guide how to backup and maintain a long-running deployment. We will add such section in near future.

**Comment by AJRubio-Montero** [comment]
Thank you very much @lopiola for the response.

> We strongly recommend using onedatify
> We do not recommend manual installation using packages, as there is quite a lot of administrative effort and knowledge required to do this correctly.

Really, it is this is not the key topic, but i will resume why we aren't using `onedatafy`, which also illustrates our needs.

Administratively, I don't see the difference between running the `onedatafy` script or executing `apt/yum` commands for the installation. Additionally, if somebody without certain knowledge of Linux/sysadmin plans to support large datasets, he is an irresponsible.

On the other hand, using pre-configured dockers are very good for CD/CI or for a fast deployment for demonstrations, but also masks basic problems, one of them is making consolidated backups. This problem is identical for virtual machines. In the MV (or docker) memory are the volatile data of your applications. Of course you can snapshot (or commit) the running MV (or docker), but you don't actually obtain a consolidated backup (especially with databases) and no manufacturer supports the direct snapshoting without some kind of service stop. Additionally,  the backup size enormously increases with snapshots. In fact, in our institution always use the recommended method for backing-up databases, it takes up less size and it always allow the recovery of the data.

Additionally, `onedatify` can be laborious depending on the underlying system. For example in our case, we are using pre-configured VMs, when I ran `onedatafy` on them (in the past), network hangs due to severe miss-configurations and I don't know why happens it. Dealing with this issue requires inspecting inside docker instances, docker-compose configuration...much time more than dealing with packets. In addition, my colleagues usually directly work with packets and services, it will allow them to basic support OneData services.

> there are other important config files and Onepanel's database (mnesia) - basically all of this, apart from logs, is required for the service to run correctly. https://github.com/onedata/onedata/blob/develop/docker/persistence-dir.py
>In case of any data corruption, you should simply restore the latest uncorrupted backup. In general, it is not possible to rebuild the metadata that was stored in the database solely based on the disk contents as there is a lot more information stored in Oneprovider's database than on disk, especially those related to data distribution between different Oneproviders. If you do not have a backup, it is not possible to bring back the previous state.

These are the clues I was requiring.  Thus, there are several kinds of data to backup:
1- Couchbase database (a.k.a. buckets)  --> with `cbbackup` and `cbrestore` commands you can perform consolidated/migrated backups -> OK.
2- Mnesia database (part of Erlang )-> I don't know how do a consolidated backup. ideas?
3- Files in  `onedata/.../etc`  -> configuration files (closed files) -> OK
4- Files in `onedata/.../var/log` -> log files, (open files for adding lines) -> Are these files needed for rebuilding the databases or are simple logs?


>For some storages, however, it is possible to run automatic storage import. You could create a new space, create an imported storage pointing to your pre-populated disk, support the space with the Oneprovider and enable import. This will make the files visible in the space and usable, but will not bring the state from before the corruption (files will have different uuids etc).

Moreover, at least with POSIX storage, if you use an existent space and you try to import data from old disk that previously were supported that space, it also recovers the metadata for the pre-existent files!!!. It is great!. 

This is nearly the behavior I want: to have the possibility of installing other OneProvider and importing the backups and disks. Will be possible? (I have tested it using Couchbase backups in the same OneProvider instance, but  I did not with new instances or when the space is supported by several instances).

(Other collateral problem is there are much other information about other spaces in Couchbase, which perhaps i don't want to restore. Only comes to my mind to performs N1QL selects, but this is other history).

Thanks in advance,
Cheers.

**Comment by lopiola** [comment]
I see your point, it is true that installation from packages allows much finer control over the configuration and persistence, I just wanted to say that it is harder to do well. The dockerized installations are nothing more than an Ubuntu image with the packages preinstalled inside and some scripts for easier maintenance. Basically by inspecting the Dockerfile you can do the same manually.

> ... but also masks basic problems, one of them is making consolidated backups. This problem is identical for virtual machines. In the MV (or docker) memory are the volatile data of your applications.

What I'm trying to say is that we **do** support consolidated backups by mapping all the persistence in docker to a single directory located on the host (mounted to the docker via volume). You are right that a backup without stopping the service is very hard or impossible - unfortunately you have to stop the docker but then it is enough to make a copy of the persistence directory (`/opt/onedata/onedatify/oneprovider_conf` on the host) - and you get a consolidated backup. We do not recommend making snapshots of the docker, this is not the way to go.

> These are the clues I was requiring. Thus, there are several kinds of data to backup:
2. Simple copy of the physical files, but when the service is stopped
4. These are simple log files, not required for the service to resume working (it will create new ones)

> This is nearly the behavior I want: to have the possibility of installing other OneProvider and importing the backups and disks. Will be possible?

If I understand correctly, you want to restore the couchbase state at the same time running import on a disk which supported a previous space? If so, it cannot work well. As I said, the import procedure creates **new metadata** in couchbase, it **does not recover** the old metadata. It will be completely detached from the old database contents. There are two separate ways you can proceed:
1. If you have a persistence (database) backup, just restore it. Old metadata will be again available in Couchbase and Oneprovider will be able to find the old files on the disk within the old space. The problem is when the metadata backup (couchbase) diverges with the data backup (the physical files on the storage). For that reason it would be best to make a correlated backup of both (persistence directory and the storage disk) and then bring back both upon any problems.
2. If you don't have a persistence backup, there is no way back. Storage import can only substantiate a new space that will have everything from the disk, but it will be a brand new space, not something "recovered" - file ids will be completely different, this and other providers will treat them as completely different.

**Comment by AJRubio-Montero** [comment]
Hello again

> What I'm trying to say is that we do support consolidated backups by mapping all the persistence in docker to a single directory located on the host (mounted to the docker via volume).

OK, I won't ask about the other methods.

> unfortunately you have to stop the docker but then it is enough to make a copy of the persistence directory
> 2. Simple copy of the physical files, but when the service is stopped


OK, thus the problem is the time spent in stopping -> backing up -> starting. 

My machine spends about 15 seconds in stopping/starting services, the backup procedure could last few minutes if only persistence directory is copied and a 10Gpbs network is used (< 2 minutes if the size is 100GB).  This can be feasible.


>The problem is when the metadata backup (couchbase) diverges with the data backup (the physical files on the storage). For that reason it would be best to make a correlated backup of both (persistence directory and the storage disk) and then bring back both upon any problems.

However, making a correlated backup of the storage disks when it takes up few TBs (even on a 10Gbps network) is unfeasible, the services will be stopped too time. Although you will only make an incremental backup, this will last more than 15 minutes per TB (obviusly depends on the data stored, but with a high number of small files, the backup spends the time testing changes of every one and the network tube never will be filled up). 

The only solution I see now is to make frecuently backups of Couchbase without stopping the database (i.e. every hour), independently from the other services (every day). If a crash happens, I will restore both, (being the persistence directory much old than the used couchbase copy), while I'm maintaining the "update data" enabled for the disk (to check if were changes since the backup).  

Would be it feasible?  Can I force the "update data" method by command?

Cheers.

**Comment by lopiola** [comment]
> However, making a correlated backup of the storage disks when it takes up few TBs (even on a 10Gbps network) is unfeasible

Yes, that's true, in general making backups of a large storage is problematic - Onedata does not change anything in this matter as we only act as a storage driver (a logical layer on top of the storage). The Oneprovider admins must have they own methods of maintaining and backing up their storage, as they would if the storage was used directly by users. 

> backups of Couchbase without stopping the database (i.e. every hour), independently from the other services (every day). If a crash happens, I will restore both

This might work, basically the other files then the couchbase persistence do not change, unless you make some changes in Onepanel (then the mnesia persistence changes).

Sorry but I didn't understand - what you mean by "update data" ?

**Comment by AJRubio-Montero** [comment]
> Sorry but I didn't understand - what you mean by "update data" ?

When I'm adding disk support to a space, I can activate the "import" and  "update" features.  The last one periodically scans the disk for changes.   

If someone writes files or moves directories after the hourly backup of Couchbase and the Oneprovider crashes, these changes will be not seen when I will recover from the backup.  However, if the "update" feature was set, at least these files/directories would appear, although their metadata were lost. I think.

 Cheers.

**Comment by lopiola** [comment]
Ah ok, I see. Yes, having this feature enabled will certainly help converge the states of the DB and storage, because if anything is different, a change will be detected and metadata will be reconciled. If a file was already imported before the backup, the ID will not change, but if it is a new one that was created after the CB backup, it will get a new ID.

**Comment by AJRubio-Montero** [comment]
Thank you @lopiola 

I will test backups by this way, and generate some unnoficial documentation. Until it will be performed I'm closing the issue.

Cheers.
