### ISSUE TITLE
files aprently with 0 Bytes when use oneclient mounts (OneProvider 19.02.5 and 20.02.4)

### ISSUE THREAD

**Issue by AJRubio-Montero** [onedata/onedata#43]
Good evening.

We are experiencing strange behaviours when we mount *Spaces* with *oneclient* against 19.02.5 and 20.02.4 releases of OneProvider.

We have an application that creates local files and then it progresively moves these files into a Space mounted with *oneclient*. 

Although files are small, the first file spends 1 minute to be moved. Rest of them seems to be moved quickly.  The actual problem is that many of these files are appearing with 0 Bytes, even at *datahub.egi.eu*, and they cannot be downloaded. 

However, files were stored in OneProvider.  This is:

```bash
[root@38c332668b15 run]# oneclient /mnt
....
RUN APP THAT CREATES LOCAL FILES AND THEN IT MOVES THEM INTO /mnt/test6/sac_xxxx 
....
[root@38c332668b15 run]# ls -alh /mnt/test6/sac_10_150.0_75600_QGSII_flat/
total 0
drwxr-xr-x 1 1034995 1073456    0 Dec 29 18:19 .
drwxrwxr-x 1 root    root       0 Dec 29 18:14 ..
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:17 DAT000703-0703-00000000024.input
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:17 DAT000703-0703-00000000024.lst.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:17 DAT000703.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT000904-0904-00000000007.input
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT000904-0904-00000000007.lst.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT000904.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:17 DAT001105-1105-00000000017.input
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT001105-1105-00000000017.lst.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:17 DAT001105.bz2
-rw-r--r-- 1 1034995 1073456  614 Dec 29 18:16 DAT001206-1206-00000000061.input
-rw-r--r-- 1 1034995 1073456 3.6K Dec 29 18:16 DAT001206-1206-00000000061.lst.bz2
-rw-r--r-- 1 1034995 1073456   14 Dec 29 18:16 DAT001206.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT001407-1407-00000000013.input
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT001407-1407-00000000013.lst.bz2
-rw-r--r-- 1 1034995 1073456    0 Dec 29 18:18 DAT001407.bz2
....
```

However if I list these files in the OneProvider:

```bash
# ls -alh sac_10_150.0_75600_QGSII_flat/
total 292K
drwxr-xr-x  2 1034995 1073456 4.0K Dec 29 19:21 .
drwxr-xr-x. 3 root    root      42 Dec 29 19:14 ..
-rw-r--r--  1 1034995 1073456  612 Dec 29 19:17 DAT000703-0703-00000000024.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:17 DAT000703-0703-00000000024.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:17 DAT000703.bz2
-rw-r--r--  1 1034995 1073456  612 Dec 29 19:18 DAT000904-0904-00000000007.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:18 DAT000904-0904-00000000007.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:18 DAT000904.bz2
-rw-r--r--  1 1034995 1073456  613 Dec 29 19:18 DAT001105-1105-00000000017.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:18 DAT001105-1105-00000000017.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:18 DAT001105.bz2
-rw-r--r--  1 1034995 1073456  614 Dec 29 19:16 DAT001206-1206-00000000061.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:16 DAT001206-1206-00000000061.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:16 DAT001206.bz2
-rw-r--r--  1 1034995 1073456  614 Dec 29 19:18 DAT001407-1407-00000000013.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:18 DAT001407-1407-00000000013.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:18 DAT001407.bz2
-rw-r--r--  1 1034995 1073456  614 Dec 29 19:17 DAT001608-1608-00000000059.input
-rw-r--r--  1 1034995 1073456 3.6K Dec 29 19:17 DAT001608-1608-00000000059.lst.bz2
-rw-r--r--  1 1034995 1073456   14 Dec 29 19:17 DAT001608.bz2
```

Can you help us with the throubleshooting?  We don't see any hint in the logs.

Cheers.
Happy new year.

**Comment by bkryza** [comment]
@AJRubio-Montero 
1. The issue with the first file is probably related to storage detection by Oneclient, which is by default performed on a first I/O operation in a space. If the Oneclient determines that it has direct access to the underlying storage of the space (e.g. a Ceph volume or S3 bucket) it reads and writes from this storage directly, which is much faster and scalable. However if it cannot detect the storage it falls back to proxy mode, where all IO operations are pushed through Oneprovider to the storage. If you know that you either want proxy or direct, please try adding `--force-proxy-io` or `--force-direct-io` to Oneclient command line, which will skip  storage detection and just use that mode. If you choose `--force-direct-io` and you will get I/O errors it means that the Oneclient does not have direct access to this storage...
2. The issue with the empty files could be related to a failed storage detection or something with metadata synchronization, could you paste the exact version of Oneclient you're using for each Oneprovider (just to be sure), you can also enable verbose logging in Oneclient (-v=3), which should give us a better idea what is happening...

**Comment by AJRubio-Montero** [comment]
Thanks @bkryza

With the option `--force-proxy-io` seems it works fine, at least with small files. 

I would swear that I have tested it before, but other problems could have been masking this behaviour, and I cannot remember when I made the tests (before or after changes in configuration).

I'm close the issue.
Cheers.
