### ISSUE TITLE
Onedatify validation email reports bad format when use some characters like "-"

### ISSUE THREAD

**Issue by alfonpd** [onedata/onedata#44]
When I use a email with characters like "-", the validation script reports bad email format.

########## Basic parameters ###########
Please enter the preety name of your oneprovider (default: oneprovider-01.localhost):
Enter a new administration password for the Oneprovider or the password will be autogenerated: XXXXXXXX
Your new password to login into Oneprovider is: XXXXXXXXXX
Please enter the email address that will be used as the emergency contact for this provider (default: ): **mymail@one-two.org**
Invalid email format. The email must match: [a-zA-Z0-9]+(.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(.[a-zA-Z0-9]+)+
Please enter the email address that will be used as the emergency contact for this provider (default: ):

**Comment by groundnuty** [comment]
fixed
