### ISSUE TITLE
Can't create subdomain delegation level 2

### ISSUE THREAD

**Issue by alfonpd** [onedata/onedata#46]
Can't create a subdomain delegation for a Oneprovider machine that is part of other subdomain. I try to create the subdomain delegation: oneprovider01.ceta-ciemat.datahub.egi.eu and oneprovider02.ceta-ciemat.datahub.egi.eu

When the script ask me for the name, I get the next error:

########### Certificates #############
You can choose to provide your own certificates or use subdomain delegation and request Onezone to help in generating the Let's Encrypt certificate for your subdomain.
Do you want use subdomain delegation to acquire a FQDN for your Oneprovider? (y/n, default: y)?: y
Please enter the subdomain for your oneprovider (auto-detected default: oneprovider01.ceta-ciemat): 
The format of the subdomain must mach the regualr expression '[ a-z0-9 ] ( [ -a-z0-9] * [ a-z0-9 ] )'. Please try again.

Regards.

**Comment by lopiola** [comment]
Hello @alfonpd,

our subdomain delegation supports only first-level subdomains, so you have to go for something like:
```
oneprovider01-ceta-ciemat.datahub.egi.eu
oneprovider02-ceta-ciemat.datahub.egi.eu
```
