### ISSUE TITLE
Error  reported by localFeedRemoveOnedataUserToCredentialsMapping 

### ISSUE THREAD

**Issue by andrea-manzi** [onedata/onedata#49]
Hello,
we are noticing that removing a  user mapping from the LUMA Local Feed on a non imported storage is giving  an error even though the mapping is actually removed from the feed

the mapping is there 

`
[Onedata REST CLI - 20.02.7]$ onepanel-rest-cli -u onepanel:$PASSPHRASE localFeedGetOnedataUserToCredentialsMapping id=$STORAGE_ID onedata_user_id=$ONEDATA_USER_ID --host https://$ONEPANEL_HOST:9443
{"storageCredentials":{"uid":"1000"},"displayUid":1000}#   
`

we try to remove it but we get an error

`
[Onedata REST CLI - 20.02.7]$ onepanel-rest-cli -u onepanel:$PASSPHRASE localFeedRemoveOnedataUserToCredentialsMapping id=$STORAGE_ID onedata_user_id=$ONEDATA_USER_ID  --host https://$ONEPANEL_HOST:9443
{"error":{"id":"errorOnNodes","details":{"hostnames":["notebooks-cesnet-00.datahub.egi.eu"],"error":{"id":"requiresImportedStorage","details":{"storageId":"7093397c7214c48e89aa2d3df81ab992ch8e65"},"description":"Cannot apply for storage 7093397c7214c48e89aa2d3df81ab992ch8e65 - this operation requires an imported storage."}},"description":"Error on nodes notebooks-cesnet-00.datahub.egi.eu: Cannot apply for storage 7093397c7214c48e89aa2d3df81ab992ch8e65 - this operation requires an imported storage."}}#
`

if we check again, the mapping is correctly removed

`
[Onedata REST CLI - 20.02.7]$ onepanel-rest-cli -u onepanel:$PASSPHRASE localFeedGetOnedataUserToCredentialsMapping id=$STORAGE_ID onedata_user_id=$ONEDATA_USER_ID --host https://$ONEPANEL_HOST:9443    
{"error":{"id":"errorOnNodes","details":{"hostnames":["notebooks-cesnet-00.datahub.egi.eu"],"error":{"id":"notFound","description":"The resource could not be found."}},"description":"Error on nodes notebooks-cesnet-00.datahub.egi.eu: The resource could not be found."}}#
`

same behaviour if we use directly the REST API

thanks
Andrea

**Comment by jakud** [comment]
Hello Andrea,

thank you very much for reporting the issue. We have just fixed it. 
The fix will be present in the 20.02.10 release.

Cheers,
Jakub
