### ISSUE TITLE
Registering new Handle service

### ISSUE THREAD

**Issue by rpaganmunoz** [onedata/onedata#51]
PROBLEM FOUND (Onezone 20.02.10): Registering the handle service “B2Handle” (from EUDAT) into OneData to manage the PIDs for the produced data within the EOSC-Synergy project (LAGO thematic service).
If I understand the OneData documentation correctly, the handle service (PID or DOI) is added by registering a REST API using a username and a password.
However, the B2Handle service requires certificate-based authentication for handling PIDs.
Does OneData support certificate-based authentication? Are there any related instructions?

**Comment by bkryza** [comment]
@rpaganmunoz Actually we do support B2Handle integration based on certificates, although it is not very well documented. In a nutshell you have deploy somewhere a small service which will proxy requests for PID registration between Onedata and B2Handle. The service source code is available here https://github.com/onedata/hps-b2handle/ , although the preferred way to run is using Docker (please make sure that the service endpoint will be accessible from your Onezone instance):
```
docker run -v $PWD/privkey.pem:/hps-b2handle/certs/privkey.pem -v $PWD/cert.pem:/hps-b2handle/certs/cert.pem onedata/hps-b2handle:1.0.0
```

Once deployed, you have to register this service in Onezone using REST API (please note that this requires oz_handle_services_create admin privilege in Onezone):

```
curl -ksS -v -H "X-Auth-Token: $TOKEN" -vvv -X POST -H "Content-type: application/json" -d @handle_service.json https://$ONEZONE_HOST/api/v3/onezone/handle_services
```
where $TOKEN is your admin token, ONEZONE_HOST is your Onezone hostname and handle_service.json has the following content:
```
{
  "name" : "PID Handle Service",
  "proxyEndpoint" : "HPS_PROXY_SERVICE_IP:8080/api/v1",
  "serviceProperties" : {
        "allowTemplateOverride": false,
        "endpoint": "https://PID_SERVICE_IP_AND_PORT/api/handles/",
        "username": "",
        "password": "",
        "prefix": "YOUR_PID_PREFIX",
        "type": "PID"
  }
}
```
where you need to replace HPS_PROXY_SERVICE_IP, PID_SERVICE_IP_AND_PORT and YOUR_PID_PREFIX with your relevant details.

Once the service is registered (in the response you will get a Onedata handle service id), you will to give some regular user access rights to this service using the following REST call:

```
curl -ksS -H "X-Auth-Token: $TOKEN" -v -X PUT -H "Content-type: application/json"  https://$ONEZONE_HOST/api/v3/onezone/handle_services/$YOUR_HANDLE_SERVICE_ID/users/$SOME_USER_ID
```

From then on the service should be available for the users when publishing open data, and PID's will be automatically minted and assigned to the open data sets in Onedata.

If you do not have admin rights to the Onezone service please let us know which Onezone instance you are using and will try to register the service for you...

**Comment by andrea-manzi** [comment]
Hi @bkryza , i guess this proxy service is already available in EGI DataHub right? cause i just registered this http://hdl.handle.net/21.T15999/NyBqJZg 

and LAGO is using the EGI DataHub, so maybe it's just a matter to give the  users access to it

**Comment by bkryza** [comment]
@rpaganmunoz @andrea-manzi Sorry, didn't realize this was EGI DataHub :-) In that case just send us the user ID's (preferably via email) who should have access to this service (it can be found under "Manage user" button)...

**Comment by AJRubio-Montero** [comment]
Hello, many thanks @bkryza  and @andrea-manzi for the help. The management of PiDs is new for us.

However, we have some questions. There is a default proxy service for B2Handle in DataHub, but what is happen with the authorization for an specific handle prefix?

LAGO has a own prefix [http://hdl.handle.net/21.12145] through SurfSARA (https://epic-pid.storage.surfsara.nl:8003/api/handles), which is managed with a specific user/certificate.  How can we securely manage these credentials in the proxy? Is it the proxy configured only for a prefix and will we need build another in our data-center?  

(There is no problem for building the proxy service in our data-center, but we would rather not maintain this service, as well as we are relying on DataHub for the OneZone instance . It is better that main centralized services were maintained with the expertised people from OneData and EGI/EOSC).

Thanks.
Cheers.

**Comment by bkryza** [comment]
@AJRubio-Montero yes you are right if you want your own certificates and prefix for B2Handle you need a separate instance of the proxy. If you don't want to manage this by yourself, we can deploy it on the EGI DataHub resources - but we'll need your user certificate - please send me an email: bkryza@gmail.com

**Comment by AJRubio-Montero** [comment]
Thanks a lot @bkryza, we will send you the credentials and we are closing this ticket.

Cheers.

**Comment by rpaganmunoz** [comment]
Thank you all
