### ISSUE TITLE
Failed to create a cluster

### ISSUE THREAD

**Issue by FL1188** [onedata/onedata#53]
Hello~~~
 **I followed the following steps to install the cluster:**
```
 # Add Onedata package repository
$ sudo sh -c 'curl -sSL  http://packages.onedata.org/onedata.gpg.key | apt-key add -'
$ sudo sh -c 'echo "deb http://packages.onedata.org/apt/ubuntu/xenial xenial main" > /etc/apt/sources.list.d/onedata.list'
$ sudo sh -c 'echo "deb-src http://packages.onedata.org/apt/ubuntu/xenial xenial main" >> /etc/apt/sources.list.d/onedata.list'

# Update package list
$ sudo apt update
$ export ONEPANEL_AUTOSTART=false # Disable automatic Onepanel start
$ sudo apt install oz-panel
$ sudo apt install cluster-manager
$ sudo apt install oz-worker
$ sudo apt install couchbase-server-community
$ sudo apt install onezone
```

**And finally I restart it：**
sudo systemctl restart couchbase-server.service

**But when I start to create a cluster in web, I can‘t create my cluster successfully, and I did not find the server or database logs about this error.
Looking forward to your help~ Thank you~**

![1](https://user-images.githubusercontent.com/63219274/138690765-31f8fe42-08eb-4582-a10a-53457933ff95.jpg)
![2](https://user-images.githubusercontent.com/63219274/138690782-ca609088-2de9-4cf3-abf7-1c0b750d9053.jpg)
![3](https://user-images.githubusercontent.com/63219274/138690795-feb21917-9228-4720-b1d8-1ae7defffd78.jpg)
![4](https://user-images.githubusercontent.com/63219274/138690808-e9eed369-a8b4-4c40-9759-66e040165cfb.jpg)

**Comment by lopiola** [comment]
Hello,

currently, the recommended way of installing the Oneprovider service is using the Onedatify script (dockerized installation). Installation from packages requires quite a complicated setup and differs depending on the machine.

The documentation for Onedatify installation can be found here: https://onedata.org/#/home/documentation/stable/doc/administering_onedata/onedatify_deploy.html

**Comment by FL1188** [comment]
Thank you very much for the answer！
When I was installing provider and distributing space for zone，I met some problems.
The following is log about error.

```
########################################
You will now be asked to provide configuration parameters:


########## Basic parameters ###########
Please enter the preety name of your oneprovider (default: ydd9966): ydd99665544
Enter a new administration password for the Oneprovider or the password will be autogenerated: password
Your new password to login into Oneprovider is: password
Please enter the email address that will be used as the emergency contact for this provider (default: liza4tmp@163.com):
liza4tmp@163.com
Absolute path where to keep oneprovider configuration and metadata (default: /opt/onedata/onedatify/oneprovider_conf):
Please enter the latitude of your provider (auto-detected default: 34):
Please enter the longitude of your provider (auto-detected default: -118):

########### Certificates #############
You can choose to provide your own certificates or use subdomain delegation and request Onezone to help in generating the Let's Encrypt certificate for your subdomain.
Do you want use subdomain delegation to acquire a FQDN for your Oneprovider? (y/n, default: y)?: y
Please enter the subdomain for your oneprovider (auto-detected default: ydd9966): ydd99665544
The FQDN of your Oneprovider is: ydd99665544.onezone.onedata.org

########### Storage Configuration #############
What storage type would you like to use? (default: posix, possible options: posix | s3 | ceph | glusterfs | swift ):
An absolute path to a directory you want use to support your Onedata POSIX storage (default: /t/root/ydd_mnt_01

####### Starting Oneprovider ########
Installation is about to start, you can observe detailed logs by executing following command in a second window:
onedatify logs

Waiting for oneprovider to start....................
Congratulations! Oneprovider have started succesfully.


curl: (52) Empty reply from server
The size of space support (you can use B, KiB, MiB, up to EiB, 1KiB = 1024B, eg. 1GiB) (auto-detected: 1.0000GiB): 15GiB

Supporting a space with 16106127360 [B] of storage  on oneprovider ydd99665544.onezone.onedata.org
Checking Oneprovider reddiness..

We were unable to support your space!

Error:
{"error":{"id":"errorOnNodes","details":{"hostnames":["ydd99665544.onezone.onedata.org"],"error":{"id":"badValueIdNotFound","details":{"key":"storageId"},"description":"Bad value: provided ID (\"storageId\") does not exist."}},"description":"Error on nodes ydd99665544.onezone.onedata.org: Bad value: provided ID (\"storageId\") does not exist."}}

You can continue to configure your Oneprovider and support your space manually via Onepanel emergency account.

Please visit:
https://ydd99665544.onezone.onedata.org:9443

and use the password:
password
to access the Onepanel emergency account.

```

**Comment by lopiola** [comment]
Hello,

I believe that there were some problems creating the storage, but the script failed to report a descriptive error. We will have to check that and improve the script so it's clearer what happens.

I think the storage creation error was caused by nonexistent path - the script won't create a mountpoint for you, it has to exist (more importantly, it has to exist in the Oneprovider docker). For convenience, by default the whole host's filesystem is mounted under `/hostfs` in the docker. So, if there actually is a path `/t/root/ydd_mnt_01` (which you provided in the script) on your machine, it should be enough to put `/hostfs/t/root/ydd_mnt_01` during the installation. 

Can you please re-run the script, with a clean installation? You may also finish configuration manually, just enter the Onepanel GUI (https://ydd99665544.onezone.onedata.org:9443) and follow the wizard.

**Comment by FL1188** [comment]
Thank you for your help ~~~
Sorry it took so long to close it.
