### ISSUE TITLE
oneclient 

### ISSUE THREAD

**Issue by FL1188** [onedata/onedata#58]
greeting! @lopiola,

I installed oneclient by `curl -sS  http://get.onedata.org/oneclient.sh | bash` several days ago and it was working properly.
But I just tried to use it a few minutes ago and found oneclient was not working, and the mount point is broken.
The terminal shows that the mount point direction is  “Permission denied” when I input “ls” command.
![image](https://user-images.githubusercontent.com/63219274/146917493-f957827e-a075-4e0b-81fb-c6a629a2c228.png)
When I input "df -h", the terminal is blocked and can not exit, instead of showing my disks.
I unmounted the old mount point  ,then the "ls" "df -h" showed the right thing.

I'd like to know that if oneclient can survive for a long time(months)? If I can use its VFS function under industry environment connecting to the oneproviders?

I will be very grateful for your help!

**Comment by bkryza** [comment]
Hi @FL1188

currently there are issues with long running Oneclient process, especially in case of Oneprovider restarts or network issues, and the only solution is to remount the oneclient. 

We are working on that of course, and hopefully in the next stable release this will be solved or at least substantially improved...

**Comment by FL1188** [comment]
Thank you very much for your answer.
Have a nice day~
