### ISSUE TITLE
Slow Oneprovider GUI with thousand spaces/storages

### ISSUE THREAD

**Issue by svobtom** [onedata/onedata#61]
Hello, 

I run an Oneprovider which supports hundreds of spaces (actually cca 1 000). Because all these spaces are imported, there are also the same number of storages. I primary work with these entities through API, but sometimes is convenient to check existing spaces or storages by web GUI on pages https://onezone_domain/onp/provider_id/i#/onedata/clusters/provider_id/storages or https://onezone_domain/onp/provider_id/i#/onedata/clusters/provider_id/spaces. 

But in versions 20.02.18 there is problem with loading such number of entities to the web page. Sometimes loading all these entities is ok, but sometimes it failed with error messages. Sometimes my web browser (Firefox 113.0.1) freeze on the page for a minute or two with message "A web page is slowing down your browser". Sometimes loading ends with no results loaded (only blank white space is displayed). Sometimes an error message is displayed (print screen attached). Find desired space/storage on the relevant page is very hard. If I find desired space/storage, I click on its toggle box, but nothing happened for a quite long while (several seconds). 

It will be very good to have some possibility of (might server-side) filtering and limiting maximal number of displayed entities on these pages.

![obrazek](https://github.com/onedata/onedata/assets/5918676/5ee7b144-9608-43bc-b967-41a48f3cfa0c)

Sometimes there are errors (print screen attached) on the page with Oneprovider overview (https://onezone_domain/onp/provider_id/i#/onedata/clusters/provider_id/overview) in boxes "Space support" and "Storages", which is probably also caused by huge number of spaces/storages. 

![obrazek](https://github.com/onedata/onedata/assets/5918676/52af3179-9b4f-4ead-8350-8d7487ca91c5)

**Comment by lopiola** [comment]
Hello,

The space browser is quite rudimentary and it was not designed to handle this many spaces at once. You can consider yourself a pioneer :) We have scheduled work in the upcoming weeks to fix this problem.

**Comment by lopiola** [comment]
Hello,

I'm happy to report that the issue has been fixed in software version 21.02.2 - we have added paging to handle large quantities of storages and spaces. The loader also now shows loading progress and does not time out trying to load everything at once.
