### ISSUE TITLE
Question about repackaging OneProvider

### ISSUE THREAD

**Issue by colakong** [onedata/onedata#7]
Hello,

I've gotten Indigo IAM working, and was using it in OneProvider storage config for S3. The storage config was to point at our S3 clone, which doesn't support [v4 auth headers](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html). The AWS libraries used by OneProvider were generating v4 auth headers, so the S3 configuration failed.

I looked to see if I could swap out the AWS libraries for something older, but got a bit confused. In the OneData git repo it looks like C++ AWS library is referenced, but in the `onedata/oneprovider:3.0.0-rc11` container I didn't find them; I found Erlang BEAM files like `/usr/lib/op_worker/lib/op_worker-3.0.0-rc11/ebin/{amazonaws_iam,s3_user}.beam.`

Am I missing something with the C++ AWS library? And is there a way you know of that I could repackage OneProvider container with an older version of AWS libraries?

**Comment by groundnuty** [comment]
@colakong did you manage to resolve this issue? or found a workaround?

**Comment by colakong** [comment]
@groundnuty I stopped looking at it and moved on to other work, until our S3 clone catches up with v4 auth support :)

**Comment by groundnuty** [comment]
@colakong we were forced to a rudimentary support for v3. Feel free to check it.
