### ISSUE TITLE
problem with small files: Resource temporarily unavailable

### ISSUE THREAD

**Issue by r5r3** [onedata/onedata#8]
Dear onedata team, 

following the admin quickstart guide, I created a setup on two machines (scenario 3, one machine for onezone and one for oneprovider). Both of these machines have a 10-Core Xeon CPU and 64 GB RAM, data was stored on SSDs. The network connection between both computers is 1GE.

On a third computer, I used the fuse-client to mount the onedata-filesystem. That worked without problems and for large files, the full network bandwidth was usable. However, for small files the performance was extremely bad. I tried to create a large number of files with a size of 2kB. It was not possible to create more then 30 files per second. After a few thousand files were created, the write process crashed with an I/O error `Resource temporarily unavailable`. At the same time, the 10-Core CPU on the oneprovider machines is fully utilized and remains fully utilized for several minutes. It is than not possible to create any new files. 

Question: is the behavior described above to be expected? Is onedata intended to share only large files without lots of changes?

**Comment by groundnuty** [comment]
@r5r3 
The symptoms you witnessed were caused by bugs, that in turn generated performance problems. We solved most of them in rc14 release. You are welcome try out the rc14 and see if your usecase works.
