### ISSUE TITLE
Problem with Ceph storage connection.

### ISSUE THREAD

**Issue by sarevok** [onedata/onedata#9]
There is a problem when trying to connect Ceph storage to OneProvider.
Ceph monitor version: 10.2.5
OneProvider: OneProvider oneprovider:3.0.0-rc11
OneProvider deployed using https://github.com/onedata/getting-started#s10
Logs attached.
[op_panel_add_ceph_storage_error.txt](https://github.com/onedata/onedata/files/886147/op_panel_add_ceph_storage_error.txt)

**Comment by groundnuty** [comment]
@sarevok can you check if this problem is still valid in rc14? we introduced many fixes in that release.

**Comment by luman75** [comment]
To connect to ceph we are using their library at version 11.1.0-1 , and our system will be supporting only Cephs which are backward compatible with this library.

**Comment by groundnuty** [comment]
@sarevok any updates? any successes? :)

**Comment by sarevok** [comment]
Unfortunately we still get errors when trying to connect OneProvided (RC17) and Ceph 12.2.0 which are the latest versions of both of them.  Logs attached.
[oneprovider_errors.txt](https://github.com/onedata/onedata/files/1310420/oneprovider_errors.txt)
![oneprovider_error](https://user-images.githubusercontent.com/36807/30538996-b718be30-9c70-11e7-938d-026791e6a060.PNG)
